### ISSUE TITLE
Azure Portal - No update Customer Managed Keys option

### ISSUE THREAD

**Issue by aidaDiazFdez** [Azure/login#100]
When updating the encryption via poweshell command (Set-AzCognitiveServicesAccount -ResourceGroupName $rsg -name $name -KeyName $key -KeyVersion $version -KeyVaultUri $uri) it is not updated in the portal to the Customer Managed Keys option.

if you check the ARM Template if it is correctly configured or if you check it via command.
![Evidence](https://user-images.githubusercontent.com/40237415/112356291-c323ff80-8cce-11eb-86d7-f5ddf8483a17.png)

**Comment by kanika1894** [comment]
Hey @aidaDiazFdez, the login action just authenticates a user to Az cli / Powershell. 
Are you saying that using this action, you are unable to get authentication on Powershell?

**Comment by aidaDiazFdez** [comment]
I get authentication and it is shown to me in the ARM Template, but it is not shown visually in the portal.

**Comment by BALAGA-GAYATRI** [comment]
Can you share your workflow here?

**Comment by BALAGA-GAYATRI** [comment]
@aidaDiazFdez 
Can you share your workflow here?

**Comment by kanika1894** [comment]
Since the authentication is successful, the issue might be with the script that is being used to perform the action.
The scope of login action is just to provide authentication as happens when we use Az cli command to login.

**Comment by kanika1894** [comment]
@aidaDiazFdez were you able to progress?

**Comment by kanika1894** [comment]
Closing issue due to no update. Please free to open in case of any issue.
