### ISSUE TITLE
Downloading action repository to self-hosted runner takes 2.5 minutes

### ISSUE THREAD

**Issue by joloEqui** [Azure/login#103]
Every time I run my workflow on my self-hosted runner it has to redownload the whole action repository which takes 2.5 minutes. This is the step in my workflow log: Download action repository 'azure/login@v1'.

I am not sure if this is a more general issue in GitHub Actions, where the action repository is redownloaded every time even if it is the exact same version being used each run. But since the other actions I use are downloaded in a matter of seconds and this action takes 2.5 minutes I opened the issue here.

Also I have looked into using the cache action, but can't figure out how to use it for caching "external" actions, or if that is possible at all, that's also why I have opened this issue.

**Comment by johanclasson** [comment]
When checking the downloaded files at `_work\_actions\Azure\login\v1` I can see that the `node_modules` folder is part of the plugin.

Can you consider compiling in the dependencies that is needed so that the `node_modules` does not need to be downloaded? The GitHub docs ([ref.](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github)) mention a tool called `vercel/ncc`.

**Comment by joloEqui** [comment]
Btw, my solution was to just use az cli to login instead of the login action.

**Comment by andrewwiebe** [comment]
Yeah same issue, its 3 mins just to download the action every single run.

**Comment by andrewwiebe** [comment]
> 
> 
> Btw, my solution was to just use az cli to login instead of the login action.

Do you have a quick code example of how you handled this?

**Comment by joloEqui** [comment]
Yep.

$Credential = ConvertFrom-Json($env:SERVICE_PRINCIPAL)
az login --service-principal -u $Credential.appId -p $Credential.password --tenant $Credential.tenant --allow-no-subscriptions

**Comment by andrewwiebe** [comment]
> 
> 
> Yep.
> 
> $Credential = ConvertFrom-Json($env:SERVICE_PRINCIPAL)
> az login --service-principal -u $Credential.appId -p $Credential.password --tenant $Credential.tenant --allow-no-subscriptions

Thank you very much for this. I will have to try this out using a github secret.

**Comment by AjayKaleMS** [comment]
> > Yep.
> > $Credential = ConvertFrom-Json($env:SERVICE_PRINCIPAL)
> > az login --service-principal -u $Credential.appId -p $Credential.password --tenant $Credential.tenant --allow-no-subscriptions
> 
> Thank you very much for this. I will have to try this out using a github secret.

I also faced this same download taking time for almost 2 mins every time.
When I tried above suggested code, I am still facing the issue. Below is my final action code:

jobs:

  build-and-deploy:
    runs-on: self-hosted
    steps:	  
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
        az login --service-principal -u $creds.appId -p $creds.password --tenant $creds.tenant --allow-no-subscriptions
        az webapp list --query "[?state=='Running']"

**Comment by BALAGA-GAYATRI** [comment]
<img width="1322" alt="Screenshot 2022-05-12 at 11 18 48 PM" src="https://user-images.githubusercontent.com/26038662/168137389-0e6ccf31-a47c-4abf-90e8-8dab65bfaea9.png">
Recently tested a few samples of the self-hosted runner download time for login action. All of them shows similar times. It is taking around 10-12 seconds including downloading, unwrapping and archiving the action repo. So closing this issue as this seems like an intermittent issue.

**Comment by kWozniak-tt** [comment]
> <img alt="Screenshot 2022-05-12 at 11 18 48 PM" width="1322" src="https://user-images.githubusercontent.com/26038662/168137389-0e6ccf31-a47c-4abf-90e8-8dab65bfaea9.png">
> 
> Recently tested a few samples of the self-hosted runner download time for login action. All of them shows similar times. It is taking around 10-12 seconds including downloading, unwrapping and archiving the action repo. So closing this issue as this seems like an intermittent issue.

@BALAGA-GAYATRI This problem unfortunately still exists.
![image](https://github.com/Azure/login/assets/70513945/e35a6554-9fe9-4a70-802a-338718ee2dc2)
#366
