### ISSUE TITLE
Trying to use it but it is failing

### ISSUE THREAD

**Issue by nd185089** [Azure/login#109]
Run Azure/login@v1
  with:
    creds: ***
    enable-AzPSSession: false
    environment: azurecloud
    allow-no-subscriptions: false
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" cloud set -n azurecloud"
Done setting cloud: "azurecloud"
Error: Az CLI Login failed. Please check the credentials. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows
Error: Error: Error: The process 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd' failed with exit code 1

I review the credentials, they are all right. But when I browse through plugin code (main.ts), something caught my eyes.
let creds = core.getInput('creds', { required: true });
        let secrets = new SecretParser(creds, FormatType.JSON);
        let servicePrincipalId = secrets.getSecret("$.clientId", false);
        let servicePrincipalKey = secrets.getSecret("$.clientSecret", true);
        let tenantId = secrets.getSecret("$.tenantId", false);
        let subscriptionId = secrets.getSecret("$.subscriptionId", false);
        let resourceManagerEndpointUrl = secrets.getSecret("$.resourceManagerEndpointUrl", false);

I am not passing the last parameter "resourceManagerEndpointUrl". Is this needed to be added in my JSON parameter?

**Comment by BALAGA-GAYATRI** [comment]
@nd185089 resourceManagerEndpointUrl is a part of the credentials in the secrets.  Please check and confirm if this is how you are generating credentials https://github.com/Azure/login#configure-deployment-credentials

**Comment by BALAGA-GAYATRI** [comment]
@nd185089 any updates on this?

**Comment by nd185089** [comment]
Yes, its working now
