### ISSUE TITLE
Certificate based auth

### ISSUE THREAD

**Issue by joelverhagen** [Azure/login#111]
Azure AD app registrations show two credential mechanisms in Azure Portal: client secret (supported today with `clientSecret`) and certificate. It would be great to support both. in this GitHub Action.

I'm envisioning a `clientCertificate` property where the content is the base64 encoded certificate content (PEM/PFX). 

The benefit of this approach is that certificates are a strong form of credential than client secret and many organizations allow a longer rotation period for certificates than secrets (which are much like passwords).

**Comment by charlie-normand** [comment]
>The benefit of this approach is that certificates are a strong form of credential than client secret and many organizations allow a longer rotation period for certificates than secrets (which are much like passwords).

Some organisations insist on certificate auth, except by exception (a convoluted process in an enterprise).  Would be great to have this so we can start using Github actions

**Comment by LauraFoulquier** [comment]
Hi, 
Is there any update on this ticket ?

Thanks !

**Comment by tulsishell** [comment]
> In the meantime, if someone is looking for a solution:
> 
> * Save the contents of the .pem file into a Github secret (make sure it follows [these guidelines](url)).
> * Create your steps as follow:
> 
> ```
> steps: 
>     - name: Write certificate to VM
>       run: |
>         touch certificate.pem
>         echo "${{ secrets.AZURE_CREDENTIALS }}" >> certificate.pem
>    
>     - name: Login via Azure CLI with certificate
>       uses: Azure/cli@1.0.4
>       with:
>         inlineScript: |
>             az login --service-principal --username <client ID> --tenant <tenant id> --password certificate.pem
> ```

I'm sorry, the link under "these guidelines" is not working. Could you please update? 
How are we to store the .pem certificate as Github secret again?

**Comment by LauraFoulquier** [comment]
Hey @tulsishell, I have updated the URL, but in a nutshell:
- Convert your pfx certificate to .pem format. It should give you a "readable" file
- Copy the text from your .pem to a GitHub secret (plain text)

**Comment by tulsishell** [comment]
> Hey @tulsishell, I have updated the URL, but in a nutshell:
> 
> * Convert your pfx certificate to .pem format. It should give you a "readable" file
> * Copy the text from your .pem to a GitHub secret (plain text)

Thank you so much @LauraFoulquier . I was able to get the Azure login action to work :)

**Comment by BALAGA-GAYATRI** [comment]
The current `azure/login` action's design doesn't include this implementation so not looking forward to implementing in near future. Since the workaround exists with CLI action, this issue will be closed.

**Comment by jiasli** [comment]
> In the meantime, if someone is looking for a solution:
> 
> * Save the contents of the .pem file into a Github secret (make sure it follows [these guidelines](https://support.radware.com/app/answers/answer_view/a_id/1018575/~/how-do-i-convert-my-certificate-from-pfx-to-pem-format%3F)).
> * Create your steps as follow:
> 
> ```
> steps: 
>     - name: Write certificate to VM
>       run: |
>         touch certificate.pem
>         echo "${{ secrets.AZURE_CREDENTIALS }}" >> certificate.pem
>    
>     - name: Login via Azure CLI with certificate
>       uses: Azure/cli@1.0.4
>       with:
>         inlineScript: |
>             az login --service-principal --username <client ID> --tenant <tenant id> --password certificate.pem
> ```

Due to a breaking change in Azure CLI 2.67.0 (https://github.com/Azure/azure-cli/issues/30283), if you want to use this solution, you need to change `--password` to `--certificate`:

```
az login --service-principal --username <client ID> --tenant <tenant id> --certificate certificate.pem
```
