### ISSUE TITLE
Need a way to enable detailed log for the failure " Az CLI Login failed" The process ‘/usr/bin/az’ failed with exit code 1`

### ISSUE THREAD

**Issue by bryantson** [Azure/login#112]
When I run an Azure Login (azure/login@v1) command through a GitHub Action pipeline, and it fails with the following log message and it does not tell much what is happening:

`/usr/bin/az cloud set -n azurecloud
13Done setting cloud: “azurecloud”
14Error: Az CLI Login failed. Please check the credentials. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows
15Error: Error: Error: The process ‘/usr/bin/az’ failed with exit code 1`

Azure GitHub Action login (https://github.com/Azure/login) repo does not show any option to enable log. What will be the best way to see exactly what caused the fail?

**Comment by BALAGA-GAYATRI** [comment]
@bryantson  can you try adding a secret **ACTIONS_STEP_DEBUG** and set the value **true** and see if it helps debug the issue.

**Comment by mathiaspet** [comment]
Hi, 
the secret produces way more output but unfortunately nothing w.r.t. error above. I'm stuck at the same point

**Comment by BALAGA-GAYATRI** [comment]
@mathiaspet  your issue addressed in  [#122](https://github.com/Azure/login/issues/122#issuecomment-864706045).
