### ISSUE TITLE
Recommended credential configuration causes unnecessary masking in GitHub logs

### ISSUE THREAD

**Issue by doug-papenthien-by** [Azure/login#113]
The recommended way of configuring the GitHub secret to contain the Azure credentials results in GitHub masking all output containing curly braces.  For multi-line secrets, GitHub treats each line of the secret as sensitive (which makes sense when you think about it).

So specifying credentials like this...
```json
{
  "clientId": "<GUID>",
  "clientSecret": "<GUID>",
  "subscriptionId": "<GUID>",
  "tenantId": "<GUID>"
}
```

...will instruct GitHub that `{` and `}` are sensitive.  Anything you echo out to the GitHub logs from this point on will mask curly braces.  This makes reading JSON in your logs less than ideal:

```
***
    "key": "value1",
    "obj": ***
        "subkey": "value2"
    ***
***
```

Fortunately, you can resolve this by specifying your secret as:
```json
{ "clientId": "<GUID>",
  "clientSecret": "<GUID>",
  "subscriptionId": "<GUID>",
  "tenantId": "<GUID>" }
```

Updating the documentation in this repo to consider this behavior would prevent others from scratching their heads wondering why their curly braces are always masked in GitHub logs.

**Comment by BALAGA-GAYATRI** [comment]
@doug-papenthien-by  Thank you for the suggestion! updated readme
