### ISSUE TITLE
Azure login action does not mention 'logout' 'cache purge' or 'account clear' actions

### ISSUE THREAD

**Issue by dstratman-fi** [Azure/login#117]
Hi GitHub Azure login team,

Just looking to see if the documentation could be updated to discuss whether any logout / cache purge / & account clear actions are needed after using this marketplace GitHub action.  We just want to be sure that the GitHub action (when run from a github hosted runner or a self-hosted runner) needs to have any of the login data cleared / purged related to the login for security purposes.  Obviously, to do this in the Azure CLI, you perform actions like 'az logout', 'az cache purge', and 'az account clear'.  It would be useful to note in the actions documentation how the login is handled (ex. it is held only in memory and then dumped after the full job with all steps on that runner is completed).  In other words, how is the login & cache and account data being kept from any possibility of re-use.

Secondly, if any of that data could be left residing on the runner, can we add a feature to have something that allows the option to ensure it is logged out, purged, and cleared to ensure clean up and any short-term way to force it in the interim.

I have noticed that if I make the last step in my job run on that runner perform an 'az logout', then an 'az cache purge' and an 'az account clear', the commands often succeed without giving me the standard "There are no active accounts", which makes me wonder if this does need to be cleaned up manually.

If this needs to be triaged to security instead of here, let me know.

Thanks!

**Comment by BALAGA-GAYATRI** [comment]
Hi @dstratman-fi ,
Thanks for the insights! We have added [documentation](https://github.com/Azure/login#az-logout-and-security-hardening) for this.  Hope it helps!

**Comment by dstratman-fi** [comment]
@BALAGA-GAYATRI  - thanks for the excellent update and the update to the docs.  That helps tremendously.  We have the need for both requirements (github-hosted runners and self-hosted runners) so your update was very helpful.  We were using the logout, purge, and account clear as 'just in cases', but this helps to level set when it is needed and when it is not as well as a way to do it though the action itself.  Thanks!
