### ISSUE TITLE
Cannot access database after enabling "Deny public network access"

### ISSUE THREAD

**Issue by tobiasdiez** [Azure/login#118]
If you set "Deny public network access" to "True" under "Connection security" in Azure Portal for a postgres database, then this login action no longer grants access and one can no longer reach the database.

**Comment by BALAGA-GAYATRI** [comment]
@tobiasdiez can you show post your workflow here for better understanding and would recommend you to try adding a secret **ACTIONS_STEP_DEBUG** and set the value **true** and see if it helps debug the issue.

**Comment by tobiasdiez** [comment]
Thanks for your response. You can find the workflow here: https://github.com/JabRef/JabRefOnline/blob/main/.github/workflows/deploy.yml The secerts are of the form
```
{
	"clientId": "....",
	"clientSecret": "....",
	"subscriptionId": "....",
	"tenantId": "...."
}
```
(with the ids as shown in the azure portal) and
```
postgresql://user:password@....database.azure.com:port/postgres?schema=public&sslmode=require
```


With "Deny public network access" set to true and "Allow access to Azure services" to No, the workflow fails: https://github.com/JabRef/JabRefOnline/runs/2814046385?check_suite_focus=true. As soon as I set it to false + Yes, it works: https://github.com/JabRef/JabRefOnline/runs/2814046445?check_suite_focus=true

Will try the debug statement later.

**Comment by BALAGA-GAYATRI** [comment]
Here are the few insights.

1. This repository's issues deals with only **Azure/login** action. As I could see in both the cases **login** was successful which clearly indicates the issue is not with this action.
2. For updating the database you are using  `yarn prisma:migrate:deploy `which is not an action. We recommend you using [azure-postgresql-action](https://github.com/marketplace/actions/azure-postgresql-action) which has firewall rules set and basically whitelists the runner ip during the execution process. You should not face this issue there.

Hope it helps!!

**Comment by tobiasdiez** [comment]
Thanks for the clarification. I was under the impression that the azure-login action should give access to one's resources. But you are right, the firewall rule is only added in the database-related azure actions, e.g. in https://github.com/Azure/postgresql/blob/3ff351152c0c93c1bba9769cc6cbc462ed685e89/src/main.ts#L25-L29

Since the azure-postgresql-action is not flexible enough to run arbitrary command accessing the database (and since there is quite some code duplication related to the firewall rule across different azure actions), I guess you can view this issue as a feature request that one can (optionally) add the firewall rule already on login.

**Comment by tobiasdiez** [comment]
How should we go forward with this? Should I open an issue at the azure-postgresql-action to be able to run arbitrary commands (and not only sql scripts), or are you considering to implement the firewall rule in the azure-login-action? In the latter case, this issue should perhaps be reopened.

**Comment by BALAGA-GAYATRI** [comment]
Hey @tobiasdiez . [Azure/cli](https://github.com/Azure/cli) action does something similar to your requirement where it takes inlinescript as an input parameter which has the commands you wish to execute on CLI. Let's know if it helps!

**Comment by tobiasdiez** [comment]
Please correct me if I'm wrong, but the purpose of the Azure CLI seems to be to manage azure resources. In my context, I want to run a script that based on the state of the repository modifies the postgresql database. In particular, the script should run in the context of the github action (to access everything that is in the repo) and not on Azure. I only need a secure way to access the database. In pseudocode:
- Login to azure
- Add temporary firewall rule
- Run scripts modifying the database
- Remove firewall rule again
- (Logout)

In principle, this is similar to how the azure-database-action work, with the difference that those only allow to run database-specific scripts (e.g. sql files) while in my case I need to run prisma migrate.

**Comment by tobiasdiez** [comment]
@BALAGA-GAYATRI can you please reopen this issue? I still couldn't find a way to add the necessary firewall rules to access the database after logging into azure using the `azure/login` action. As outlined above, I think it would be nice if the login action and not the database-specific actions are taking care of the firewall exception. In the end, after you logged in you want to have access to your resources, right?

**Comment by tobiasdiez** [comment]
@BALAGA-GAYATRI ping

**Comment by BALAGA-GAYATRI** [comment]
@tobiasdiez We shall look into it and let you know about this issue.

**Comment by tobiasdiez** [comment]
Any news about this @BALAGA-GAYATRI
