### ISSUE TITLE
login action would not accept my AZURE_CREDENTIALS secret

### ISSUE THREAD

**Issue by mathiaspet** [Azure/login#122]
Hi,

I'm working on a subscription where I cannot create SPs myself due to access restrictions. Thus, I cannot just copy the json produced by the `az ad sp create-for-rbac`  cmd. However, I have access to the registered app, subscription etc. So built the json myself. I added it as a gh secret and used the login action. 

Fails with 
`Error: Az CLI Login failed. Please check the credentials. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows
Error: Error: Error: The process '/usr/bin/az' failed with exit code 1`  

However, if  logging in manually using az login with the values from the credentials json and the PW referenced by clientSecret works. 

Is there a special format, that I have to adhere?
Is it even possible to use a handcrafted credentials file?

Thx

**Comment by BALAGA-GAYATRI** [comment]
Hi @mathiaspet  ,
So the basic format of credentials secret generated after using this command `az ad sp create-for-rbac` looks like this.
```
{
 "clientId": "",
 "clientSecret": "",
 "subscriptionId": "",
 "tenantId": "",
 "resourceManagerEndpointUrl": "",
 "activeDirectoryEndpointUrl": "",
 "activeDirectoryGraphResourceId": "",
 "sqlManagementEndpointUrl": "",
 "galleryEndpointUrl": "",
 "managementEndpointUrl": ""
}

```
for this action, the first 5 fields of this json are mandatory. Make sure you configure them correctly. It is possible to use handcrafted credentials as long as they are working. 
Hope it helps!
