### ISSUE TITLE
Login action failing because of Azure credentials secret

### ISSUE THREAD

**Issue by oscardalmau-r3** [Azure/login#126]
Hi,

I am trying to use the az login action on the ubuntu GH runner but I am getting the following error:
Error: Az CLI Login failed. Please check the credentials. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows
Error: Error: Error: The process '/usr/bin/az' failed with exit code 1

The SP that I have to use was already created, so I have manually created the format from the GH secret containing the Azure credentials, as suggested in this comment: https://github.com/Azure/login/issues/122#issuecomment-864706045

I have also enabled ACTIONS_STEP_DEBUG but the output doesn't help with this.

Any suggestions?

Thanks

**Comment by oscardalmau-r3** [comment]
It was my fault. Closing this.

**Comment by MaciejBoguta** [comment]
> It was my fault. Closing this.

what was the fault about? got the same error and I am sure the credentials are fine since they're also used in the same workflow to authenticate within terraform

**Comment by IronSean** [comment]
@oscardalmau-r3 I'd also like to know what the issue was in case it's my issue too.
