### ISSUE TITLE
 Login failed  Please check the credentials -  Error: Input required and not supplied: creds

### ISSUE THREAD

**Issue by olguin** [Azure/login#143]
I am defining a github action to build and deploy azure functions when a new PR is created.

So if in the github action I use the trigger
on [push]

When the action is fired it works okay.

BUT if I change the action main.yml file, so that the build/action is triggered
on [pull_request]

The az login step fails with the error:

**Error: Az CLI Login failed. Please check the credentials. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows
Error: Error: Input required and not supplied: creds**

I got the AZURE_CREDENTIALS by following the documentation, running the command:

`az ad sp create-for-rbac --name "some_funct_app" --sdk-auth --role contributor  --scopes /subscriptions/some_sub_id/resourceGroups/some_resource/providers/Microsoft.Web/sites/some_function_app`

Then I inserted the result in the github repository as a secret secrets.AZURE_CREDENTIALS also following the documentation. 

I did that on the main repository and also on the forked repository from which I am creating the Pull request.

FYI Including here the main.yml azure/login invocation:

```
 - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: false

```

and so when I send a new PR it is returning the error:

**Error: Az CLI Login failed. Please check the credentials. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows
Error: Error: Input required and not supplied: creds**

Please help!
thank you.

**Comment by kanika1894** [comment]
Hey @olugin, when you say:
> I inserted the result in the github repository as a secret secrets.AZURE_CREDENTIALS
What's the name of your secret? Just checking that it should be AZURE_CREDENTIALS and not secrets.AZURE_CREDENTIALS.
Can you please confirm about this?

**Comment by olguin** [comment]
Hello @kanika1894 , I set the secret's name as defined in the documentation: AZURE_CREDENTIALS

I am only accessing it from the github workflow definition using secrets. AZURE_CREDENTIALS

**Comment by kanika1894** [comment]
@olguin, thanks for confirming.
The code snippet that you pasted from the workflow file seems to have indentation issues, can you fix those?

Ideally, with the details that you are providing, it should have worked. With the error message that you stated, the action doesn't seem to identify the secrets that you provided. Trying to figure out what could be the possible reason...

**Comment by olguin** [comment]
Hi Kanika, 

 in the github workflow file the indentation is as follow:

   - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: false


Also please do notice that it is not throwing an error when the "on" trigger is "push". Only if I change it to "pull_request"

**Comment by kanika1894** [comment]
Hey @olguin,

Ahhh! So there's the catch. When the workflow is triggered from a forked repository, they can't have access to the secrets. 
More details [here](https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow).
Instead of pull_request trigger, can yo please try  pull_request_target?

**Comment by olguin** [comment]
Tried it, it worked!! @kanika1894, thank you!

I did noticed the documentation saying that secrets were not passed to forks but I was creating the same secret in my fork (we are part of the same organization than main repository) so I thought that will be enough and bypass this secret's restriction but it did not.

Thank you again, you can close this issue thread then because it is not an actual issue (not sure if I can do it myself).

**Comment by kanika1894** [comment]
I understand. But the workflow gets executed in the scope of the base repository, so the presence of secrets in the forked repo doesn't help in the scenario. 
Glad that your issue is resolved with the pull_request trigger.
