### ISSUE TITLE
Install az CLI if not present

### ISSUE THREAD

**Issue by dylan-smith** [Azure/login#154]
This task doesn't work on self-hosted runners if the az cli is not already installed. Would be nice if this actions would automatically install the cli if not found like alot of other actions that rely on CLI's do.

Alternatively, provide a separate setup-azure-cli type action that we can call first.

**Comment by BALAGA-GAYATRI** [comment]
Closing this issue as the same issue being tracked here - https://github.com/Azure/login/issues/104
