### ISSUE TITLE
How to generate AZURE_CREDENTIALS for a subscription level?

### ISSUE THREAD

**Issue by IvanJobs** [Azure/login#165]
Hi there,

According to 
```
az ad sp create-for-rbac --name "myApp" --role contributor \
                            --scopes /subscriptions/{subscription-id}/resourceGroups/{resource-group} \
                            --sdk-auth
                            
  # Replace {subscription-id}, {resource-group} with the subscription, resource group details

  # The command should output a JSON object similar to this:

  {
    "clientId": "<GUID>",
    "clientSecret": "<GUID>",
    "subscriptionId": "<GUID>",
    "tenantId": "<GUID>",
    (...)
  }
  ```
this is to generate AZURE_CREDENTIALS for a specific resource group, but how can I generate it for a subscription level?
I try to update the --scopes to subscriptions level, but it comes out without any keywords with clientId/clientSecret.

Any help would be appreciated, thanks.

**Comment by BALAGA-GAYATRI** [comment]
Hey @IvanJobs  you may try

```
az ad sp create-for-rbac --name "myApp" --role contributor \
                            --scopes /subscriptions/{subscription-id}  \
                            --sdk-auth
```
for subscription level scope. More info on scopes can be found[ here](https://docs.microsoft.com/en-us/azure/role-based-access-control/scope-overview).
