### ISSUE TITLE
Update all environment variable references to match the standard naming conventions

### ISSUE THREAD

**Issue by jongio** [Azure/login#167]
OIDC docs reference the following env vars
https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-cli%2Clinux#create-github-secrets

AZURE_CLIENTID
AZURE_TENANTID
AZURE_SUBSCRIPTIONID

Azure SDK and previous Azure CLI implementations use:
https://github.com/Azure/azure-sdk/blob/main/_includes/tables/environment_variables.md

AZURE_CLIENT_ID
AZURE_TENANT_ID
AZURE_SUBSCRIPTION_ID

The standard has an underscore before "ID"

Can we please update the OIDC implementation to use these?

I see them referenced here:
https://github.com/Azure/login/blob/3e6f6e7d1bb95c18e868c5bfd87fef1743ba292d/README.md
https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-cli%2Clinux#create-github-secrets
https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure

**Comment by BALAGA-GAYATRI** [comment]
Hey @jongio Thanks for pointing out. We will update the documentation for the same.:)

**Comment by BALAGA-GAYATRI** [comment]
Changed readme with the same.

**Comment by jongio** [comment]
@BALAGA-GAYATRI - This location still has no underscore https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication

**Comment by jongio** [comment]
Here as well https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#create-github-secrets

**Comment by BALAGA-GAYATRI** [comment]
Will update here also. Thanks :)

**Comment by BALAGA-GAYATRI** [comment]
This is also done. Closing this issue.
