### ISSUE TITLE
OIDC id_token / id-token inconsistency

### ISSUE THREAD

**Issue by jongio** [Azure/login#168]
I see "id-token" in OIDC docs:
https://github.com/Azure/login#github-action-for-azure-login
https://github.com/Azure/login#sample-workflow-that-uses-azure-login-action-using-oidc-to-run-az-cli-linux

But "id_token" in official GH docs
https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#permissions

Please make consistent

**Comment by BALAGA-GAYATRI** [comment]
@N-Usha Can you take care of this?

**Comment by BALAGA-GAYATRI** [comment]
@jongio Done updating in GH-doc as well.
