### ISSUE TITLE
actions/checkout fails with permissions: id-token: write

### ISSUE THREAD

**Issue by jongio** [Azure/login#169]
Include this in yaml:

```
permissions:
  id-token: write


    steps:
      - name: Checkout
        uses: actions/checkout@v2
```

And it will fail with:

```
  remote: Repository not found.
  Error: fatal: repository 'https://github.com/jongio/***/' not found
  The process '/usr/bin/git' failed with exit code 128
  Waiting 20 seconds before trying again
```

We need to also have:

```
permissions:
  id-token: write
  contents: read
```
Since most actions will checkout the repo code, then we need to include the `contents: read` permission in the samples.

**Comment by BALAGA-GAYATRI** [comment]
Hey @jongio, Can you share your workflow here? 
[Here](https://github.com/BALAGA-GAYATRI/azure-login-action-tests/blob/main/.github/workflows/azure_login_oidc_test.yml) is mine and [run logs](https://github.com/BALAGA-GAYATRI/azure-login-action-tests/runs/4163044810?check_suite_focus=true). It works for me without `contents` permission also. I want to know if the concern is specific to any case.

**Comment by jongio** [comment]
Does it work for you without "contents: write"?

**Comment by BALAGA-GAYATRI** [comment]
Yes, For a public repo it works. For private repo it is asking for permissions. We are updating our sample workflow with this permissions for the same.

**Comment by BALAGA-GAYATRI** [comment]
Closing this issue as readme was updated with the same :)

**Comment by jongio** [comment]
@BALAGA-GAYATRI - This location doesn't have it: https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-cli%2Clinux#add-federated-credentials

**Comment by BALAGA-GAYATRI** [comment]
Thanks @jongio. We will update here also!

**Comment by jongio** [comment]
I think this can be closed. I have verified fixed in msdocs

**Comment by BALAGA-GAYATRI** [comment]
Yes. Updates are done! Closing this issue.
