### ISSUE TITLE
Update docs to remove instructions about installing a custom azure cli build

### ISSUE THREAD

**Issue by jongio** [Azure/login#170]
Here and probably other places:
https://github.com/Azure/login#sample-workflow-that-uses-azure-login-action-using-oidc-to-run-az-cli-linux
https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure
https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux

Remove bit about requiring a custom azure cli build

**Comment by BALAGA-GAYATRI** [comment]
Hey @jongio. We have added the explicit build step to install latest az-cli to support the latest OIDC login in login action. So once the runners are updated we will remove it in our samples and docs. Till then it is mandatory for the users to add this step for leveraging OIDC login.

**Comment by jongio** [comment]
I have confirmed that it was removed from those locations.
