### ISSUE TITLE
OIDC https://token.actions.githubusercontent.com/ should be https://token.actions.githubusercontent.com

### ISSUE THREAD

**Issue by jongio** [Azure/login#175]
Here: 
https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-cli%2Clinux#add-federated-credentials

Has:
```
az rest --method POST --uri 'https://graph.microsoft.com/beta/applications/<APPLICATION-ID>/federatedIdentityCredentials' --body '{"name":"<CREDENTIAL-NAME>","issuer":"https://token.actions.githubusercontent.com/","subject":"repo:organization/repository:environment:Production","description":"Testing","audiences":["api://AzureADTokenExchange"]}' 
```

It should be:
```
az rest --method POST --uri 'https://graph.microsoft.com/beta/applications/<APPLICATION-ID>/federatedIdentityCredentials' --body '{"name":"<CREDENTIAL-NAME>","issuer":"https://token.actions.githubusercontent.com","subject":"repo:organization/repository:environment:Production","description":"Testing","audiences":["api://AzureADTokenExchange"]}' 
```

https://token.actions.githubusercontent.com without a slash at the end.

If you have a slash, then you get this error:

```
Error: : AADSTS70021: No matching federated identity record found for presented assertion. Assertion Issuer: 'https://token.actions.githubusercontent.com'. Assertion Subject: 'repo:jongio/ghazoidctest1:ref:refs/heads/main'. Assertion Audience: 'api://AzureADTokenExchange'.
```

This is in a lot of places: https://github.com/search?q=azure+https%3A%2F%2Ftoken.actions.githubusercontent.com&type=Code

**Comment by BALAGA-GAYATRI** [comment]
This is updated in action readme and MS docs. @juliakm /@n-usha what about the [other places](https://github.com/search?q=azure+https%3A%2F%2Ftoken.actions.githubusercontent.com&type=Code) ? Whom should we contact for the updates?

**Comment by BALAGA-GAYATRI** [comment]
Closing this issue as the official docs are updated.
