### ISSUE TITLE
OIDC:Automate the app creation and FIC attaching process

### ISSUE THREAD

**Issue by jongio** [Azure/login#176]
Azure CLI instructions here: https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-cli%2Clinux#create-an-active-directory-application-and-service-principal

Do not work as-is.

In reality, this is what is needed to get it all setup:
https://github.com/jongio/github-azure-oidc/blob/main/oidc.sh

**Comment by BALAGA-GAYATRI** [comment]
### Create an active directory application and service principal:

1. Create an active directory application.
    ``` 
    az ad app create --display-name myApp
    ```
    This command will give a JSON output which has `appId` which is your `client-id`. The same JSON has `objectId` which is `APPLICATION-OBJECT-ID` and is used in creating federated credentials with graph api calls.

2. Create a service principal. Replace $APP-ID with above generated appId.
     ```
      az ad sp create --id $APP-ID
     ```
    This command will generate another JSON which has different `objectId` which is called `assignee-object-id` and will be used in the next step.
3. Create a new role assignment by subscription and object. By default, the role assignment will be tied to your default subscription. Replace $SUB-ID with your subscription id and $ASSIGNEE-OBJECT-ID with above generated `assignee-object-id` .
    ```
    az role assignment create --role contributor --subscription $SUB-ID --assignee-object-id  $ASSIGNEE-OBJECT-ID --assignee-principal-type ServicePrincipal
    ```

**Comment by jongio** [comment]
Can you make the commands runnable?  So the user doesn't have to copy and paste and mess with variables, etc.

**Comment by BALAGA-GAYATRI** [comment]
Hey @jongio! Can you raise a PR against readme with a bash script which you using. Also please make it as simple and generic as possible.

**Comment by jongio** [comment]
We should figure out best way to do this.  The process isn't easy. https://github.com/jongio/github-azure-oidc/blob/main/oidc.sh

Wasn't the az cli going to wrap this?

**Comment by BALAGA-GAYATRI** [comment]
Yes. Till that time users can use the script. If the effort is considerable you may work on this. Otherwise we can wait for CLI.

**Comment by BALAGA-GAYATRI** [comment]
We have [app creation and FIC attaching process](https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#use-the-azure-login-action-with-openid-connect) available using azure portal as well which makes it much easier for customers to add and manage new FICs and apps. So closing this issue.
