### ISSUE TITLE
OIDC graph calls cannot be made in GitHub Codespaces

### ISSUE THREAD

**Issue by jongio** [Azure/login#177]
If I try this:

```
az rest --method POST --uri "https://graph.microsoft.com/beta/applications/${APP_OBJECT_ID}/federatedIdentityCredentials" --body "{'name':'prfic','issuer':'https://token.actions.githubusercontent.com','subject':'repo:${REPO}:pull-request','description':'pr','audiences':['api://AzureADTokenExchange']}"
```

In a codespace, then I get this:

```Creating federatedIdentityCredentials...
AADSTS530003: Your device is required to be managed to access this resource.
Timestamp: 2021-11-18 00:28:12Z
To re-authenticate, please run:
az login --scope https://graph.microsoft.com//.default
```

When I run `az login --scope https://graph.microsoft.com//.default`

I get this:
![image](https://user-images.githubusercontent.com/2163001/142313036-227ecb7e-2869-412f-9014-95a119e603f5.png)

I think it is saying the codespace itself isn't managed by Admin

**Comment by kaverma** [comment]
@BALAGA-GAYATRI , can we move this to cli repo ?

**Comment by BALAGA-GAYATRI** [comment]
@jongio https://github.com/Azure/azure-cli/issues/21025 Filed an issue in Az-cli repo and it will be tracked there. Feel free to communicate any latest insights on this issue there itself. Closing this issue here.
