### ISSUE TITLE
OIDC pull-request should be pull_request

### ISSUE THREAD

**Issue by jongio** [Azure/login#178]
All of the docs, samples, and portal use pull-request, but OIDC only works with pull_request.

If I use pull-request, then the action fails with

```
Error: : AADSTS70021: No matching federated identity record found for presented assertion. Assertion Issuer: 'https://token.actions.githubusercontent.com'. Assertion Subject: 'repo:jongio/github-azure-oidc:pull_request'. Assertion Audience: 'api://AzureADTokenExchange'.
Trace ID: 9974950b-11aa-46ec-a15c-11b678fd0400
Correlation ID: 35c88236-8f85-4376-9288-99763b067d7c
Timestamp: 2021-11-18 04:25:44Z
```

![image](https://user-images.githubusercontent.com/2163001/142351808-49bf2a5e-1897-4ea0-8f08-bf36dc04575c.png)

**Comment by BALAGA-GAYATRI** [comment]
Hey @jogio your subject claim still shows `'repo:jongio/github-azure-oidc:pull_request'` where you used `_` instead of `-`. 
You should use `pull-request` in your subject claim instead of `pull_request` according to samples provided [here](https://github.com/Azure/login/tree/master#microsoft-graph) and portal as well.

**Comment by jongio** [comment]
Yeah, I'm saying pull-request does not work.  Only pull_request works for me.

**Comment by BALAGA-GAYATRI** [comment]
We would be changing our docs for the same.

**Comment by kjyam98** [comment]
Good find @jongio - we will update the Azure Portal UX

**Comment by guidoiaquinti** [comment]
What's the right subject identifier I should use to allow any action from the repo?

**Comment by jongio** [comment]
@BALAGA-GAYATRI or @kjyam98 - Can you see question above?  I had the same question.  It would be good to have a full list of all the possible subjects in a clear table with answers to the questions like above.

@guidoiaquinti - In my case, I setup the FIC to my main branch so any PRs to that branch would work.  If you want all branches, then I think you need to use a GH environment, but I haven't tried that yet.

**Comment by guidoiaquinti** [comment]
@jongio  I might be doing something wrong but it doesn't seems to work in my case:

> Error: : AADSTS70021: No matching federated identity record found for presented assertion. Assertion Issuer: 'https://token.actions.githubusercontent.com'. Assertion Subject: 'repo:PostHog/charts-clickhouse:ref:refs/heads/e2e_azure'. Assertion Audience: 'api://AzureADTokenExchange'.

you can see the action run [here](https://github.com/PostHog/charts-clickhouse/runs/4351388359?check_suite_focus=true). 

[This](https://github.com/PostHog/charts-clickhouse/pull/204) is the PR it's running against (PR to merge into `main` from `e2e_azure`). 

I'm using `repo:PostHog/charts-clickhouse:ref:refs/heads/main` as _Subject identifier_ for the federated credential. If I use `repo:PostHog/charts-clickhouse:ref:refs/heads/e2e_azure` everything works as expected.

**Comment by BALAGA-GAYATRI** [comment]
@kjyam98 Do we have an ETA for this updation? @N-Usha / @kjyam98 Do we have any solution for @guidoiaquinti's question- 
>What's the right subject identifier I should use to allow any action from the repo? I would like to run a CI action every time a push event (on any branch) is triggered.

**Comment by N-Usha** [comment]
@kjyam98 - Can you please update the status on this issue at Azure's end?

> What's the right subject identifier I should use to allow any action from the repo? I would like to run a CI action every time a push event (on any branch) is triggered.

There is an additional claim in the OIDC token for "event" that triggered the workflow (CI in this case) but since Azure doesn't yet support any additional claims, am afraid this scenario can't be supported using only the subject claim.

**Comment by jongio** [comment]
pull_request works for me.

**Comment by kjyam98** [comment]
> @kjyam98 - Can you please update the status on this issue at Azure's end?

@N-Usha @jongio I filed a bug for the subject identifier format issue and tagged you both on it. FYI I only found the issue in Azure Portal...I didn't see it referenced in any docs examples.

**Comment by BALAGA-GAYATRI** [comment]
It works fine now. Thanks, @kjyam98. Closing this issue as the UI is updated with `pull_request` .
