### ISSUE TITLE
log in form validation 

### ISSUE THREAD

**Issue by Danmirz18** [Azure/login#191]
https://code.sololearn.com/WjMn6A8mB0bR/?ref=app

**Comment by BALAGA-GAYATRI** [comment]
@Danmirz18 Can you be more specific about your issue? This repository's issue forum deals with azure login action.

**Comment by BALAGA-GAYATRI** [comment]
@Danmirz18 Closing this issue as the problem statement seems unclear. Feel free to reopen if the problem is occurring while using `azure/login` action.
