### ISSUE TITLE
Azure login action does not function if the client secret starts with hyphen

### ISSUE THREAD

**Issue by chapitos** [Azure/login#192]
If the Azure creds clientSecret starts with hyphen the Azure login action will fail with the following error:

`Error: : argument --password/-p: expected one argument`

It seems that the clientSecret is passed to az login using -p and not using -p= which is needed according to az login documentation if the clientSecret starts with a hyphen.

**Comment by AjayKaleMS** [comment]
Hi @chapitos  - We have implemented a fix in a forked branch. We would like you to try your workflow on below action instead of original one(azure/login@v1)

`AjayKaleMS/login@releases/v1
`
If this action works for you for secrets with and without hyphen start, then we can make the changes in original Azure/Login.

Thanks in advance for your co-operation.

**Comment by chapitos** [comment]
@AjayKaleMS: have you tested your code fix?

**Comment by AjayKaleMS** [comment]
Yes @chapitos - We have already tested it but still we want to make it sure if it is indeed working for the inputs you are facing issue with.
Please do let us know result from your side.
Thanks.

**Comment by chapitos** [comment]
@AjayKaleMS your fix is not working so I am not sure how it passed your tests. The action is throwing now a different error: AADSTS7000215: Invalid client secret is provided. 

Your change is putting the secret between quotes, which is not correct (quotes are perceived as part of the secret). Please see my comment on your PR. According to az login documentation, passwords starting with '-' need to be given with -p=secret and not -p secret. This method will also work for other secrets. So in essence, you do not need if-else logic, just use -p=secret when building arguments

**Comment by AjayKaleMS** [comment]
Thanks @chapitos for quick response on this. Actually we manually inserted '-' at the beginning of our correct client secret and this removed the original error `'Error: : argument --password/-p: expected one argument'` . This was the reason we wanted it to be tested with your inputs.

As per your comments, I have made the changes which is secret is passed in the `-p=<secret>`

Request you please test the changes again on the same below branch and kindly let us know it it works.

`AjayKaleMS/login@releases/v1
`
Thanks again.

**Comment by AjayKaleMS** [comment]
@chapitos - could you please try again as there was a block completion error - I corrected it now.

Below is final code block to handle secrets:

```
if (enableOIDC) {
                commonArgs = commonArgs.concat("--federated-token", federatedToken);
            }
            else {
                  commonArgs = commonArgs.concat("-p=", servicePrincipalKey);
            }   
```

**Comment by chapitos** [comment]
My question is related to change you made in the src/main.ts. This is still using the quotation for the password having '-' and not -p=secret.
Why is this also not changed to use -p=secret?

**Comment by AjayKaleMS** [comment]
@chapitos - Because after compiling and building main.ts, it finally is reflected in `lib/main.js` , so for the testing purpose I am directly putting the changes there in forked branch.

Could you test your secrets with hyphen?
Thanks

**Comment by chapitos** [comment]
Same error: Error: : AADSTS7000215: Invalid client secret is provided.

**Comment by AjayKaleMS** [comment]
Yes - both `src/main.ts` and `lib/main.js` are updated with same code `-p=<secret>`

**Comment by chapitos** [comment]
Here is the code of the azure login step:

`- name: Azure Login
        uses: AjayKaleMS/login@releases/v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}`

The error is, as mentioned above the same as above:

Error: : AADSTS7000215: Invalid client secret is provided.

**Comment by AjayKaleMS** [comment]
@chapitos - In the meantime, till the time I am working on this specific hyphen starting secret issue, can I request you to alter or regenerate the secrets(most probably new ones will not start with hyphen), so that your work will be unblocked using them.

Please let us know if you have any thoughts.

Thanks

**Comment by chapitos** [comment]
@AjayKaleMS 
My work is not blocked as I am using az login command from the a step of my workflow to do the login and it is working fine (with -p=secret). I have opened this issue once I noticed that the action is not working for secrets starting with hyphen.

**Comment by AjayKaleMS** [comment]
@chapitos - Good to hear that work is not blocked. We are working on it and will keep on updating the progress here.

Thanks again for all your co-operations.

**Comment by hoppeeri** [comment]
got the same issue here, the ai suggestions don't help.
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/68911210/152960294-494fe3da-562c-491e-8296-2eb946fd3794.png">

**Comment by hoppeeri** [comment]
bump

**Comment by kgage-fi** [comment]
Same error for me.

**Comment by BALAGA-GAYATRI** [comment]
In order to get unblocked with this scenario please use [Azure/cli@v1](https://github.com/azure/cli) action and provide `az login <arguments>` in the input. Make sure to follow [this](https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#use-hyphen-characters-in-arguments) while using the command there. Since a workaround is provided here, closing this issue.

**Comment by fredrkl** [comment]
IMHO: a bit odd to close this issue as it is a bug. Maybe update the documentation with this workaround?
