### ISSUE TITLE
subscriptionId and tenantId as secrets

### ISSUE THREAD

**Issue by tburgdorfcso** [Azure/login#193]
Hello, why are subscriptionId and tenantId marked as secrets ([Source](https://github.com/Azure/login/blob/db989b30605ff229e9f1de292a8f0aa043ee48b1/src/main.ts#L92))?

```
tenantId = secrets.getSecret("$.tenantId", true);
subscriptionId = secrets.getSecret("$.subscriptionId", true);
```

This is breaking some of our workflows since we need to share those ids between jobs which is not possible when they are getting masked.

Currently, we are using version 1.3.0 where they were not masked.

**Comment by BALAGA-GAYATRI** [comment]
@tburgdorfcso you need to pass them as individual secrets when you opt for OIDC auth. For non-OIDC it is still the same object. Ideally, it should work like before. Let me know the issue in detail and can share your workflow.

**Comment by tburgdorfcso** [comment]
We are using non-OIDC at the moment like this:

```
- name: Azure login
  uses: Azure/login@v1.3.0
  with:
    creds: ${{ secrets.AZURE_CREDENTIALS_133CBA31 }}
```

With every version above 1.3.0, we face the issue that the subscriptionId and tenantId are getting masked (`::add-mask::{value}`) and they can't be used as job outputs anymore.

In 1.3.0 the ids were loaded like this:

```
let tenantId = secrets.getSecret("$.tenantId", false);
let subscriptionId = secrets.getSecret("$.subscriptionId", false);
```

\>1.3.0:

```
tenantId = secrets.getSecret("$.tenantId", true);
subscriptionId = secrets.getSecret("$.subscriptionId", true);
```

The flag is whether the value should be seen as a secret and getting masked.

**Comment by BALAGA-GAYATRI** [comment]
@tburgdorfcso I understand the concern. But the reason for deciding to mask these values is, it is considered as PII data so it is recommended to treat them as secrets thereby preventing them from exposing to console logs. In your jobs which are dependent on these values, I would suggest you to read from secrets and parse them inside your script. It is not so complicated. You can refer [main.ts](https://github.com/Azure/login/blob/master/src/main.ts#L65-L77) in this action itself for the implementation. Thanks!
