### ISSUE TITLE
Custom Context Scope?

### ISSUE THREAD

**Issue by TheOnlyWei** [Azure/login#202]
Right now, it seems the azure/login@v1 step applies the context to all console application sessions. It doesn't seem like there is any scope option like the below:

https://docs.microsoft.com/en-us/powershell/azure/context-persistence?view=azps-7.1.0#save-azure-contexts-across-powershell-sessions

Would be useful to have a feature such as a "scope:" property that could be used to limit the context to the current process, so it doesn't affect another process connecting to a different environment. E.g., a user might have an Azure Stack environment and an Azure Cloud environment. The user might fetch common resources from Azure Cloud and then switch to Azure Stack environment to use them. This context change will break similar parallel code execution if it is across all applications. 

In general, if process A has just logged into Azure Cloud and process B logs into Azure Stack right after, then process A, expecting to be in Azure Cloud context, will throw an error because it's actually trying to retrieve these resources that are not available from Azure Stack.

**Comment by neerajram** [comment]
As per the [doc](https://docs.microsoft.com/en-us/powershell/module/az.accounts/connect-azaccount?view=azps-5.7.0), if you specify the -Scope Process the Az Context will be bound to that specific PS Process.

Can this be done using the azure/login@v1 action? As mentioned above, this can be helpful for us in running parallel jobs in the same VM.

**Comment by BALAGA-GAYATRI** [comment]
@TheOnlyWei We shall look into the issue and keep you posted.

**Comment by BALAGA-GAYATRI** [comment]
@TheOnlyWei I want to understand if using `azure/login@v1` action multiple times in your workflow can help you switch the environments. Ideally, it should solve your problem.

**Comment by TheOnlyWei** [comment]
@BALAGA-GAYATRI Nope, using azure/login@v1 multiple times doesn't help log in in multiple contexts in parallel. The context is a single context across multiple applications. As my main post above said, because of this shared context, if one application logs into Azure, and then another application logs into Azure Stack, then the context has changed from Azure to Azure Stack. Azure and Azure Stack are not the same product.

**Comment by BALAGA-GAYATRI** [comment]
@TheOnlyWei Thank you for the clarification. Can you try using [multiple jobs ](https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow)with each job using login action for different environments? This will help if your jobs are independent. If your jobs are dependent you can try running them sequentially also and see if it helps.

**Comment by TheOnlyWei** [comment]
Hi @BALAGA-GAYATRI I already mentioned that the context is shared across applications (i.e., once you log into PowerShell, you log into the same context whether you're using Git Bash or Command Prompt). Using multiple jobs doesn't do anything.

Yes, obviously running jobs sequentially solves the problem. But that would defeat the purpose of having multiple Github Actions runners running a single pipeline. But this isn't really a problem that should be worked around by the customer, but an opportunity for enhancement by modularizing or containing azure/login to separate contexts so it can use multiple contexts simultaneously. PowerShell already has this feature.

**Comment by BALAGA-GAYATRI** [comment]
@TheOnlyWei 
I'm just wondering if the below steps can help you achieve your desired state.
1. Use `azure/login@v1` in your workflow with `enable-AzPSSession: true `
2. And then in the next step use `azure/powershell@v1` action where the `inlineScript` contain 
    `Connect-AzAccount -Scope Process`
Do give it a try and let us know if that works.

**Comment by BALAGA-GAYATRI** [comment]
Hope the workaround helped you. If not, since you are already tracking it in CLI repo, we can reopen if CLI provides the support for the same.
