### ISSUE TITLE
The parameter "enable-AzPSSession: true" causes delays in Actions

### ISSUE THREAD

**Issue by PedroEss** [Azure/login#204]
I have figure out that the parameter "enable-AzPSSession: true" causes that run last approx 1min 20 sec, where without parameter **5 seconds**. I thought it will be a few more seconds with parameter but not that much.

**Comment by BALAGA-GAYATRI** [comment]
Hey @PedroEss. Looks like PowerShell login is taking more time for you. We shall investigate this.

**Comment by BALAGA-GAYATRI** [comment]
This issue is already being tracked in https://github.com/Azure/login/issues/119. So closing it here.
