### ISSUE TITLE
Az CLI Login failed

### ISSUE THREAD

**Issue by sundareshwarank** [Azure/login#211]
I am using the latest version of v1.4.3 while logging in I am getting the error as 
![image](https://user-images.githubusercontent.com/100189451/157643757-f920a0fe-fa49-4ebc-999a-125a4ae76b87.png)
I have stored in the secrets in different name (AZURE_CREDENTIALS_DEV_TEST). 
 I already have working deployment with the same setup with (AZURE_CREDENTIALS) will it be the issue?

**Comment by BALAGA-GAYATRI** [comment]
@sundareshwarank You can share your workflow file for understanding the issue better. The valid credentials secret name should match with the one you are referring to in your workflow.

**Comment by BALAGA-GAYATRI** [comment]
@sundareshwarank We are assuming the issue might be temporary (creds issue/ SPN creation issue etc.). Let us know if you are still facing the issue.

**Comment by sundareshwarank** [comment]
It got resolved. Thanks for following up with me.
