### ISSUE TITLE
Why is Unicode Character U+202F in action.yml

### ISSUE THREAD

**Issue by briglx** [Azure/login#215]
Opening the action.yml file shows the U-202F code in various locations:

![image](https://user-images.githubusercontent.com/1304774/161867544-940b633f-52e5-493b-b9e0-975d88b96d66.png)

**Comment by BALAGA-GAYATRI** [comment]
@briglx we shall investigate this and keep you posted.

**Comment by BALAGA-GAYATRI** [comment]
Hey @briglx. It's just a NARROW NO-BREAK SPACE character and was perhaps introduced previously to prevent an automatic line break. It's just like space and shouldn't affect any functionality. If you are not comfortable with the view you can disable highlighting it and it shows up like a normal space. In vscode you can do this by moving the cursor on that character and adjusting the settings.

**Comment by briglx** [comment]
Hi @BALAGA-GAYATRI, thanks for the clarification.
