### ISSUE TITLE
Parameter to return a jwt with expiry calculated from utc

### ISSUE THREAD

**Issue by daniel-olivieri-fmgl** [Azure/login#217]
Having a few issues with tokens coming back that have already expired, I believe this is to do with Timezone. The calling pipeline is from a pod where the Timezone is set to UTC but the closest login endpoint will likely be set to utc+10.

Is it currently possible to correct this with some kind of 'isUtc' parameter/env variable?

Perhaps the action can do some correction logic so that the token returned will be for a future or past datetime corrected for utc?

**Comment by BALAGA-GAYATRI** [comment]
@daniel-olivieri-fmgl this shall be investigated and we will you keep you posted.

**Comment by BALAGA-GAYATRI** [comment]
@daniel-olivieri-fmgl @zoebosschaart All the token times are in UTC only. That shouldn't be a problem. 
>By default, Azure access tokens issued during OIDC based login could have limited validity. This expiration time is configurable in Azure.

https://github.com/Azure/login#github-action-for-azure-login ⬆️ 
Currently, the token available for login in our action has limited validity and it expires after that. However, one can [configure the validity](https://docs.microsoft.com/en-us/azure/active-directory/develop/configure-token-lifetimes) in the portal to extend it. This is the  [enhancement request](https://github.com/Azure/login/issues/180) which is being tracked to provide a refresh token mechanism for this action.
