### ISSUE TITLE
❓ Set range of tags from repo in GitHub federated token in the subject identifier?

### ISSUE THREAD

**Issue by andrewconnell** [Azure/login#220]
Can you set a range of tags as the subject identifier for the federated credential? Seems I can only specify a single tag... is that a limit?

I've been able to configure a federated credential by explicitly setting the tag name, but this is really only useful as a "one-time" credential? My intention is to authenticate on ANY tag, just like you can authenticate on any pull request.

I've tried different wildcard options, but can't figure out if this is supported or, if so, what works.

## scenario

- I have a GH workflow that's triggered when a release is published in the repo:

    ```yaml
    on:
      workflow_dispatch:
      release:
        types:
          - published
    ```

- part of this workflow involves logging in to Azure using the `azure/loginv1** action
- I've setup a federated credential to make this work, but it only works if I explicitly set the exact name of the tag
- what I need is to be able to login when any tag is updated
- here's what I've tried and what works... assume org **MyOrg**, repo **MyRepo**, and the tag **3.0.2**:
  - ✅  repo:MyOrg/MyRepo:ref:refs/tags/3.0.2
  - ❌  repo:MyOrg/MyRepo:ref:refs/tags/3.0.*
  - ❌  repo:MyOrg/MyRepo:ref:refs/tags/*
  - ❌  repo:MyOrg/MyRepo:ref:refs/tags/**

![Screen Shot 2022-04-27 at 6 32 09 AM](https://user-images.githubusercontent.com/2068657/165501516-5f8763f7-75bb-4511-b02e-3d3726dd3ed1.png)

**Comment by smokedlinq** [comment]
Just ran into this myself. Advice on how to work with releases would be appreciated.

**Comment by andrewconnell** [comment]
@smokedlinq I also opened https://github.com/MicrosoftDocs/azure-docs/issues/92100... did that first before I thought it might be more appropriate for the GH action (this repo). Mentioning for your tracking...

**Comment by BALAGA-GAYATRI** [comment]
Hey @andrewconnel. Currently, regex support is not provided. You have to pass individual tags/branches for the subject claim. However, we shall keep you updated if we have any information about AD's roadmap to address this. Thank you.
