### ISSUE TITLE
Update dependency - Node.js 12 reached end of security updates at the end of April 2022

### ISSUE THREAD

**Issue by prisamuel** [Azure/login#225]
This still appears to be using Node 12, which reached the end of life for security updates at the end of April 2022. Can you please update this to using a later version of NodeJS. 

https://endoflife.date/nodejs

https://github.com/Azure/login/blob/e021afe0dc2c3f2f22e22420d8cf7a75ca46513e/action.yml#L37

**Comment by BALAGA-GAYATRI** [comment]
Addressed it in [v1.4.5](https://github.com/Azure/login/releases/tag/v1.4.5)

**Comment by BALAGA-GAYATRI** [comment]
Thank you @prisamuel for pointing it out
