### ISSUE TITLE
Preview in the web interface doesn't appear

### ISSUE THREAD

**Issue by Ba4bes** [Azure/login#226]
When you create or edit a workflow in the browser, you can use the assistant at the right side of the screen.
When you search (and find) the Azure Login Action, it doesn't show a preview of the YAML to copy paste. See screenshot:

![image](https://user-images.githubusercontent.com/43912004/170259970-16fad450-cc5d-4a54-9fc0-904054b33640.png)

That is de default version that is shown. When you change the version to v1.4.4, it shows the expected behavior:

![image](https://user-images.githubusercontent.com/43912004/170260098-c1013df0-448a-497e-a966-7b829de12de2.png)

- Tested this in three different browsers with two different users
- This also appears with the [Azure ARM deploy Action](https://github.com/Azure/arm-deploy) (Haven't created an issue there yet)
- I haven't found any issues with the few other Azure Actions I clicked through.
- I am not able to reselect v1 after selecting a minor version. If I look at other actions, I don't see the combination of major and minor version. So maybe the v1 tag in the same context as the other versioning causes this behavior?

**Comment by BALAGA-GAYATRI** [comment]
Hey @Ba4bes 
We follow [this process](https://github.com/Azure/actions/blob/main/docs/release-process.md) for release management. It could have occurred because of updating the major version with the latest release. You can use the one suggested for the latest release(`v1.4.4`) with which the major version(`v1`) is always updated.

**Comment by Ba4bes** [comment]
But isn't this a bug? 
None of the other Azure actions have this, only this one and the Azure ARM deploy Action.

This is the one for Azure web app, you can see the version directly here
![image](https://user-images.githubusercontent.com/43912004/172615992-ef8370ed-b78a-4a4f-8e23-c8c53b208284.png)

The fact that you cannot see the code directly is confusing for beginners and an unexpected result. What you give as a suggestion is a workaround, not a solution.
