### ISSUE TITLE
Login with service principal fails: The received access token is not valid: at least one of the claims 'puid' or 'altsecid' or 'oid' should be present

### ISSUE THREAD

**Issue by emassimi** [Azure/login#233]
Hi, I have followed the [instructions](https://github.com/Azure/login#configure-a-service-principal-with-a-secret) on how to login via service principal, and I'm getting the following error in the pipelines: 

```
(InvalidAuthenticationToken) The received access token is not valid: at least one of the claims 'puid' or 'altsecid' or 'oid' should be present. If you are accessing as application please make sure service principal is properly created in the tenant.
Code: InvalidAuthenticationToken
```

I'm not sure whether I'm missing anything, but googling for that error doesn't seem to yield anything particularly useful. However, this doesn't seem like an error on my end as I've followed the instructions to the letter, any help will be appreciated.

Thank you.

**Comment by tgillitzer** [comment]
@emassimi I got the same error.   I reverted to version 1.1 of the action and then it worked fine.   I didn't try other versions yet.

@BALAGA-GAYATRI maybe this should be re-opened?   Or should I open a new issue?
