### ISSUE TITLE
Setting AZURE_CREDENTIALS as a secret breaks Github best practices

### ISSUE THREAD

**Issue by arnaud-tincelin** [Azure/login#236]
From https://docs.github.com/en/actions/security-guides/encrypted-secrets:

> To help ensure that GitHub redacts your secret in logs, avoid using structured data as the values of secrets. For example, avoid creating secrets that contain JSON or encoded Git blobs.

As a result of setting AZURE_CREDENTIALS as a secret, the secret content can be displayed in the console in our workflows.
I believe the example `creds: ${{ secrets.AZURE_CREDENTIALS }}` should be removed from the readme and the input `creds: ` value should instead be built from simple (non-json) secrets or removed from the action.

**Comment by BALAGA-GAYATRI** [comment]
Hi @arnaud-tincelin. Thank you for raising this concern. We have documented this as an alternative way to pass secrets. Please check it out.
> If you want to pass Subscription ID, Tenant ID, Client ID, and Client Secret as individual parameters instead of bundling them in a single JSON object (creds) to address the [security concerns](https://docs.github.com/en/actions/security-guides/encrypted-secrets) for Non-OIDC login, below snippet can help with the same.
> ```
> - uses: Azure/login@v1
>    with:
>      creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
> ```
Also one can leverage the OIDC login mechanism in this action for more secure login.
