### ISSUE TITLE
If secrets start with a dash (-), parameters are parsed incorrectly

### ISSUE THREAD

**Issue by santiagxf** [Azure/login#238]
When using a JSON credentials where the `clientSecret` starts with a `-`, then the login fails.

Example configuration:

```json
{
    "clientId": "XXXXXX-XXXX-XXXX-XXXXX-XXXXXXXXXX",
    "clientSecret": "-123456789135456789456",
    "subscriptionId": "XXXXXX-XXXX-XXXX-XXXXX-XXXXXXXXXX",
    "tenantId": "XXXXXX-XXXX-XXXX-XXXXX-XXXXXXXXXX"
}
```

Error:
`: argument --password/-p: expected one argument`

When the secret is replaced with one without the `-`, authentication works as expected. This is problematic for systems that do automatic rotation of secrets.

**Comment by kgage-fi** [comment]
We have been experiencing this same issue when our secrets are cycled.

**Comment by BALAGA-GAYATRI** [comment]
Already addressed here https://github.com/Azure/login/issues/192. So closing it.
