### ISSUE TITLE
Empty array returned

### ISSUE THREAD

**Issue by gsuttie** [Azure/login#24]
Hi folks

When I run this I get the following: -

 Run az webapp list --query "[?state=='Running']"4s
Run az webapp list --query "[?state=='Running']"
  az webapp list --query "[?state=='Running']"
  shell: /bin/bash -e ***0***
  env:
    AZURE_HTTP_USER_AGENT: 
[]

So nothing returned, but If I run the same command using the Azure CLI I get results returned as I have a number of websites running.

**Comment by asranja** [comment]
Can you give more context regarding the action that you are using and the operation that you are trying to perform ?

**Comment by aksm-ms** [comment]
Closing this issue, please reopen if needed. Please provide additional info to debug further.
