### ISSUE TITLE
Login fails when the service principal key starts with '-'

### ISSUE THREAD

**Issue by janjongerden-tomtom** [Azure/login#249]
When the service principal secret starts with `-`, a [known bug](https://github.com/Azure/azure-cli/issues/7054) in the az cli is triggered, and the login action fails with:

```
Error: : argument --password/-p: expected one argument
```

The workaround is to use the `-p=<the_secret>` syntax instead of `-p <the_secret>`.

I see there's actually already [an open PR](https://github.com/Azure/login/pull/241) that would fix this.

**Comment by BALAGA-GAYATRI** [comment]
Sorry for the delayed response. We shall take a look and let you know about the changes. Thanks!

**Comment by shubhamdeodia** [comment]
any updates on this issue ?

**Comment by marvinbuss** [comment]
I can also confirm that this causes the GH Action to fail.

**Comment by BALAGA-GAYATRI** [comment]
We have acknowledged the issue. We shall let you know the updates. Thanks!

**Comment by ondrelogin** [comment]
Hello Gayatri @BALAGA-GAYATRI 

I was able to recreate this issue while going through an AKS learn module w/the github project [mslearn-aks-deployment-pipeline-github-actions](https://github.com/MicrosoftDocs/mslearn-aks-deployment-pipeline-github-actions).

I ran into the issue in Unit 10 of the [learn module](https://learn.microsoft.com/en-us/training/modules/aks-deployment-pipeline-github-actions/10-exercise-deploy-workflow) when asked to create a secret.

```
az ad sp create-for-rbac --role Contributor --scopes /subscriptions/<SUBSCRIPTION-ID> --sdk-auth
```

After running the az cli, command, you should get a json payload similar to
```
{
  "clientId": "<guid/>",
  "clientSecret": "-x68Q~fJhoGVA35Vbo68K5m4TsLzoLR5kqzxido3",
  "subscriptionId": "<guid/>",
  "tenantId": "<guid/>",
  ...
}
```

If the "clientSecret" starts with a dash, then that service principal is an error condition. To work around the issue for the learn module, I deleted the service principal and created a new one. For you, Microsoft, you can try and recreate service principals until you get one with a "-" `clientSecret`.

To delete the service principal, you will need the id, to get the id, get the guid taht is the "clientId" and run the following command.

```
az ad sp list --filter "appId eq '<clientId/>'" -o table
```

You should get the "Id" as the 2nd column. Then you can delete the service principal and try again repeating the `az ad sp create-for-rbac` statement until you get a _"bad"_ one.

```
az ad sp delete --id "<Id/>"
```

For those who need a work around, recreating a service principal and deleting the _"bad"_ one might be the best alternative, with the az cli commands above can be helpful.

Reference links (note both are the same actual links, just different anchors/fragment)
https://learn.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#az-ad-sp-list
https://learn.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#az-ad-sp-delete

**Comment by RUBenGAMArrarodRiguEZ-ToMtOm** [comment]
Has it been tested with some sensible values? For example the hyphen like mentioned here?

**Comment by Andrei15193** [comment]
I've encountered a similar issue, it wasn't with a leading dash in the password, but with some non-alphanumeric characters. Basically, whenever I wanted to use the `--password` argument it didn't work, but it did work when I did not supply this argument and it asked for it after running the command. This was useful when testing, however I needed this to run in a pipeline. Redirecting the standard input did not work either, it was asking for the `--password` argument in that case.

The workaround I did find is to dump the password in a text file and then supply it with `Get-Content -Raw`, that managed to get the authentication working. I'm using PowerShell Core for my pipelines as it is cross-platform and way.

```pwsh
Set-Content '$password' `
  -Path './this-is-a-secret.txt'
az login `
  --service-principal `
  --allow-no-subscriptions `
  --tenant $tenantId `
  --username $username `
  --password (Get-Content -Raw './this-is-a-secret.txt')
```

This is ok for a pipeline as files will get cleared, in case of potential security leaks this can be wrapped in a `try..finally` (see https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_try_catch_finally)

```pwsh
try {
  Set-Content '$password' `
    -Path './this-is-a-secret.txt'
  az login `
    --service-principal `
    --allow-no-subscriptions `
    --tenant $tenantId `
    --username $username `
    --password (Get-Content -Raw './this-is-a-secret.txt')
}
finally {
  Remove-Item './this-is-a-secret.txt' `
    -ErrorAction SilentlyContinue
}
```

Hope it helps!

**Comment by iCodeSometime** [comment]
Still an issue.

**Comment by tuskajozsef** [comment]
@BALAGA-GAYATRI the fix was merged, could you release it to Github Marketplace?

**Comment by Simonzhaohui** [comment]
I'm using `azure/login@v1` in workflow, and hit this issue again:
```
Run azure/login@v1
/usr/bin/az cloud set -n azurecloud
Done setting cloud: "azurecloud"
Note: Azure/login action also supports OIDC login mechanism. Refer https://github.com/azure/login#configure-a-service-principal-with-a-federated-credential-to-use-oidc-based-authentication for more details.
Error: : argument --password/-p: expected one argument

Error: 
Examples from AI knowledge base:
az login --service-principal -u http://azure-cli-2016-08-05-14-31-15 -p VerySecret --tenant contoso.onmicrosoft.com
Log in with a service principal using client secret. Use -p=secret if the first character of the password is '-'.

az login --service-principal -u http://azure-cli-2016-08-05-14-31-15 -p ~/mycertfile.pem --tenant contoso.onmicrosoft.com
Log in with a service principal using client certificate.

az login -u johndoe@contoso.com -p VerySecret
Log in with user name and password. This doesn't work with Microsoft accounts or accounts that have two-factor authentication enabled. Use -p=secret if the first character of the password is '-'.
```

**Comment by cvs79** [comment]
Any ideas on when does this fix will get released. the code is in but we are waiting for some process to happen? Last release was from sept 2022 but the code did change in the mean time so this action is due a new release

**Comment by YanaXu** [comment]
We're planning the release. Thank you for your patience.

**Comment by joshft91** [comment]
Is there any timeline for release? We ran into this issue today as well.

**Comment by Simonzhaohui** [comment]
Any update for this issue ?

**Comment by YanaXu** [comment]
Hi @joshft91 , @Simonzhaohui , @martinsolberg , we're planning to release a new version next Month. Sorry to keep you waiting. Since the source code is ready in **master** branch, if it blocks you somehow, you can use a workaround solution like [this](https://github.com/Azure/login/issues/340#issuecomment-1624796136).

**Comment by YanaXu** [comment]
This fix is included in the latest release. Please try **v.1.5.0**.
