### ISSUE TITLE
CodeQL v1 will be deprecated 

### ISSUE THREAD

**Issue by jbenaventem** [Azure/login#254]
The CodeQL action v1 will deprecated on december 7Th.

It`ll be good update to version 2

**Comment by BALAGA-GAYATRI** [comment]
Hi @jbenaventem , This repository deals with only azre/login issues. Can you please explain the issue in detail and where exactly changes would be required

**Comment by jbenaventem** [comment]
Hi  @BALAGA-GAYATRI 

You can see the modified files on the associated pull request #253

To can use this action in our organizations we should check several security checks, and we need that the actions verified these controls successfully.

For that, we use CodeQL and dependaboot tools in a similar way that you. Is for that we've seen that the action used in codeql YAML file will be deprecated on 7Th December, for that reason we need to improve the codeql action v2 for our continuous security testing

**Comment by BALAGA-GAYATRI** [comment]
Thank you for the detailed description and PR. We will take a look and merge it.

**Comment by BALAGA-GAYATRI** [comment]
Merged the PR and closing this issue
