### ISSUE TITLE
Please help delete all references or connections between robertc5084@outlook.com and google workspace acct. robert@drcooper.org.

### ISSUE THREAD

**Issue by GoogleCoop** [Azure/login#255]

**Comment by BALAGA-GAYATRI** [comment]
Hello @GoogleCoop , this repository issue forum deals with only issues regarding azure login through github actions. Since your issue doesn't seem like one, I'm closing this.

**Comment by GoogleCoop** [comment]
Service? The problem with geeks is they tell you "wrong" but never tell you what right is. Very, very poor service agenda
