### ISSUE TITLE
Feature: OpenID Connect support for AzureUSGovernment and AzureChinaCloud

### ISSUE THREAD

**Issue by arnoldna** [Azure/login#257]
- Added OpenID Connect (ODIC) support for AzureUSGovernment and AzureChinaCloud

**Comment by BALAGA-GAYATRI** [comment]
Hi @arnoldna, thanks for raising this issue. We are marking this as an enhancement and will post the updates here.

**Comment by BALAGA-GAYATRI** [comment]
@udayxhegde Is OIDC login supported for government clouds? If not, do we have any timelines for this?

**Comment by some-natalie** [comment]
Related #298

**Comment by some-natalie** [comment]
Not stale, closed by #258

**Comment by MoChilia** [comment]
Closing this issue for now. It has been solved by #321.
