### ISSUE TITLE
[Azure Portal bug] Wrong Subject value generated via the Portal for Federated Credential in User Managed Identities

### ISSUE THREAD

**Issue by hansmbakker** [Azure/login#261]
There is a bug in the Azure Portal that affects the creation of Federated Credentials for **User Managed Identities** using the template for Github Actions. Creation of Federated Credentials for Service Principals via the Azure Portal using the template for Github Actions is not affected.

What happens:
The generated `Subject` identifier field of Federated Credential contains a slash (`/`) instead of a colon (`:`) after the Entity type which breaks authentication from GitHub Actions to Azure using the `Azure/login` action.

The Github Actions template for User Managed Identities uses the format
```
repo:{Organization}/{Repository}:environment/{Environment}
```

while the Github Actions template for Service Principals uses the format
```
repo:{Organization}/{Repository}:environment:{Environment}
```

A workaround is to set the `Subject` identifier field using the azure cli (using `az identity federated-credential update`) to the proper value.

**Comment by BALAGA-GAYATRI** [comment]
Hi @hansmbakker, we will take a look at the issue and share the updates. Thanks!

**Comment by hansmbakker** [comment]
I could not reproduce the issue anymore today...
