### ISSUE TITLE
Warning in workflow about nodejs version

### ISSUE THREAD

**Issue by Kbs56** [Azure/login#263]
It looks like GitHub will be deprecating NodeJS version 12. When using the azure/login function this warning is received: 
![image](https://user-images.githubusercontent.com/25680651/200022467-7938614e-056e-4805-a9c7-f0d683236a9b.png)

Here is the text from the warning: 
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: azure/login

**Comment by BALAGA-GAYATRI** [comment]
Hi @Kbs56, thanks for raising the issue. We shall take a look at this.

**Comment by BALAGA-GAYATRI** [comment]
Fixed it

**Comment by Piedone** [comment]
This was fixed here, BTW: https://github.com/Azure/login/commit/14a755a4e2fd6dff25794233def4f2cf3f866955#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6L37 It's part of 1.4.5.
