### ISSUE TITLE
Clarify OIDC based login expiry

### ISSUE THREAD

**Issue by matsest** [Azure/login#269]
I've been using the OIDC based login, and the support from this action for it is great! However, I have stumbled across that tokens used for OIDC based logins does expire, and that it seemingly is not a method in this action to configure it (client side)

The README states

> Note:
> 
> By default, Azure access tokens issued during OIDC based login could have limited validity. This expiration > time **is configurable in Azure**.

Is it possible to clarify (in the README)

1) What is the default expiry time (or where to find it for a given app/federated credential)?
2) Provide a link (MS docs/Learn) to where this expiration time can be configured?

The docs around these topics vary across Azure / Entra / Identity / Azure AD so it might be somewhere I haven't already looked, but this question has come up from customers I've been working with who's looking to change from secrets based to OIDC based login using this action.

**Comment by BALAGA-GAYATRI** [comment]
Hi @matsest,
Here is the doc for [understanding azure access-token lifetime](https://learn.microsoft.com/en-us/azure/active-directory/develop/access-tokens#access-token-lifetime)
and the [doc for configuring them](https://learn.microsoft.com/en-us/azure/active-directory/develop/configure-token-lifetimes)
However, some customers are reporting problems with configuring them. We are working with AD team to come up with better solutions. 
https://github.com/Azure/login/issues/180#issuecomment-1241746853
We shall address them soon in our readme

**Comment by BALAGA-GAYATRI** [comment]
Mentioned the above doc in the Readme. The other details about the current issue are being tracked in https://github.com/Azure/login/issues/180. Hence closing this issue.
