### ISSUE TITLE
Security: Potential leak of az secrets on cmdline.

### ISSUE THREAD

**Issue by thesattiraju** [Azure/login#27]

**Comment by asranja** [comment]
We are already masking the secrets in the action. Did you find out any specific case where we have secrets leaking on the cmdline ?

**Comment by ds-ms** [comment]
https://github.com/Azure/k8s-create-secret/issues/3 

You could check this thread for more info

**Comment by aksm-ms** [comment]
@ds-ms Currently az cli does not have a way to handle this. Environment variables are not supported for authentication and there is no way to login using file. The only way to login using service principal is using :

https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest#sign-in-with-a-service-principal

**Comment by BALAGA-GAYATRI** [comment]
In the latest OIDC support added to the login action, we aren't asking for any password information from the user for login. So closing this issue.
