### ISSUE TITLE
[Feature Request] Output data returned from az login command

### ISSUE THREAD

**Issue by hansmbakker** [Azure/login#275]
I would like to obtain the data returned from the `az login` command that the github action performed.

Specifically, after logging in I would like to obtain the `objectId` of the principal, so that I can use it for role assignments.

Alternatives considered:
- ~get it with another call like `az ad signed-in-user show --query id -o tsv` but that requires a redundant call~ this does not work when `azure/login` was used with a managed identity and OIDC
- pass the `objectId` as a parameter / env var
- use `az identity show -n <someName> --resource-group <someRg> --subscription <subscriptionID> --query principalId -o tsv`

**Comment by BALAGA-GAYATRI** [comment]
We have marked it as an enhancement and will prioritize accordingly. Thanks!

**Comment by jiasli** [comment]
A similar feature request was created for Azure CLI itself: https://github.com/Azure/azure-cli/issues/22776

The easiest way to get the object ID of the sign-in identity without additional HTTP call is to **decode the access token and look for the `oid` claim**. However, this approach is discouraged by security team and OAuth definition. For details, see https://github.com/Azure/azure-cli/issues/22776#issuecomment-1420236057

**Comment by MoChilia** [comment]
Closing this issue for now. Let's track this feature request in https://github.com/Azure/azure-cli/issues/22776.
