### ISSUE TITLE
Allow specifying  `creds` and `subscription-id`

### ISSUE THREAD

**Issue by onionhammer** [Azure/login#276]
It appears that you can only specify one or the other, but it would be useful to be able to override settings like `subscription-id` in `creds` if present for cases where you have one credential with access to multiple subscriptions on different environments

**Comment by BALAGA-GAYATRI** [comment]
As of now,  we are able to override the creds object values with individual credentials that are present in input. So if you give both `creds` and individual ones like - `subscription-id`, `client-id` , `tenant-id`. The later will be applied. Hope that answers your question.

**Comment by onionhammer** [comment]
@BALAGA-GAYATRI bump

**Comment by BALAGA-GAYATRI** [comment]
Answered here - https://github.com/Azure/login/issues/282#issuecomment-1357209694
