### ISSUE TITLE
Error: Az CLI Login failed

### ISSUE THREAD

**Issue by sudharsanpunniyakotti** [Azure/login#278]
I'm using azure/login@v1 to GHA to Azure CLI , 
I'm getting below error . 

```Error: Az CLI Login failed. Please check the credentials and make sure az is installed on the runner. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows```

Below is the workflow . 

```name: Run Azure Login 
on: [push]

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux]
    steps:
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: "Run az commands"
        run: |
          az ad list 

```

**Comment by kbocock-krg** [comment]
I wanted to call attention to the fact that this is the current supported way of using a client secret and not just adding the addition of a secret param to the with block in the oidc example. Very strange thought process.

**Comment by sudharsanpunniyakotti** [comment]
Hi ,

I have also tried this block below initally . It doesn't work . 

```on: [push]

name: AzureLoginSample

jobs:
build-and-deploy:
    runs-on: [self-hosted, linux]
    steps:

    - name: Log in with Azure
        uses: azure/login@v1
        with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}```

**Comment by sudharsanpunniyakotti** [comment]
Self-hosted doesn't have AZ cli .
