### ISSUE TITLE
How to Generate Azure AD level credential and use it in Github Action 

### ISSUE THREAD

**Issue by sudharsanpunniyakotti** [Azure/login#279]
I have requirement for login and access Azure AD level from GHA . Is it possible use service principal AD level login using azure/login@v1.4.3 with client_Id and client_Secret

**Comment by BALAGA-GAYATRI** [comment]
Hi, I didn't get your question completely. If I understand it correct, you are asking for service principal login using `client-id` and `client-secret` which is supported in the login action using `azure/login@v1` 
Please go through https://github.com/Azure/login#configure-deployment-credentials for more details.

**Comment by BALAGA-GAYATRI** [comment]
Marking this issue as closed. Feel free to reopen in case you face any issue.
