### ISSUE TITLE
Add capability to login without Subscription ID for Service Principal

### ISSUE THREAD

**Issue by dipesharora** [Azure/login#29]
Add the capability to login without Subscription ID mapped to Service Principal using _--allow-no-subscriptions_ option in _az login_. It is typical for use cases where one may have added a service principal to allow access to Azure Key Vault to get values for keys, secrets, etc. however, don't want to give any other permissions to ensure the least privilege. Users should be able to select if the SPN has permissions on the subscription or not.

e.g. _az login --service-principal -u <spn> --password <clientseceret> --tenant <tenantid> --allow-no-subscriptions_

**Comment by iornstein** [comment]
Is there any sort of work around to add "--allow-no-subscriptions" for the time being?

**Comment by aksm-ms** [comment]
@iornstein if you want to use --allow-no-subscription, you can set input "allow-no-subscriptions: true". For inputs please refer [https://github.com/Azure/login/blob/master/action.yml](https://github.com/Azure/login/blob/master/action.yml)

**Comment by aksm-ms** [comment]
Closing this issue since support is added now in v1 and can be used by adding input "allow-no-subscriptions: true" in workflow.
