### ISSUE TITLE
Documentation suggests creating secret in JSON format

### ISSUE THREAD

**Issue by MikeFindsThings** [Azure/login#292]
The current documentation for this action suggests storing the output of the service principal creation in a GitHub Actions secret. The output of this command is a JSON object. [GitHub advises not to store secrets that contain JSON.](https://docs.github.com/en/actions/security-guides/encrypted-secrets#naming-your-secrets)

If the secret is created with the JSON object as advised, any workflows utilizing [outputs and inputs](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs) will fail, as the GHA runner will block any attempts at potentially exposing a secret.

**Comment by BALAGA-GAYATRI** [comment]
Hi @MikeFindsThings , thank you for raising this issue. 
We have already documented this - https://github.com/Azure/login#configure-deployment-credentials
and encourage users to provide credentials separately provide credentials.

**Comment by MikeFindsThings** [comment]
Respectfully, users are not encouraged to store credentials separately. The 2nd bullet point in the documentation you linked to states:

"Store the output of the below [az cli](https://learn.microsoft.com/cli/azure/?view=azure-cli-latest) command as the value of secret variable, for example 'AZURE_CREDENTIALS'"

The third bullet point much further down the steps advises passing the individual components to "address the [security concerns](https://docs.github.com/actions/security-guides/encrypted-secrets) for Non-OIDC login", but does not address the fact that the earlier point is counter to GitHub's recommendations.
