### ISSUE TITLE
Output  generated by az ad sp create-for-rbac does not work with azure credentials 

### ISSUE THREAD

**Issue by clmcgrath** [Azure/login#294]
I used `az ad sp create-for-rbac`  to generate a credentials file for azure login 
what was generated does not match what is seemingly expected by the  documentation 

what was generated by az cli is 

```
{
  "appId": "***",
  "displayName": "azure-cli-2023-01-27-22-47-45",
  "password": "***",
  "tenant": "***"
}
```
it doesnt seem to generate many of the fields expected by the documentation like clientid endpoint etc 

from the documentation:
```
 {
   "clientId": "<GUID>",
   "clientSecret": "<STRING>",
   "subscriptionId": "<GUID>",
   "tenantId": "<GUID>",
   "resourceManagerEndpointUrl": "<URL>"
   (...)
 }
 ```
 using the generated output reults in a login failed error in my action script 
 
 
![image](https://user-images.githubusercontent.com/452012/215222778-2c851ca0-a64b-4537-a6ad-95f083fac9ee.png)

 
 i know the service principal works from testing with az cli  
 has some terminology changed ?
or is something causing the unexpected output to be generated 
is there a way to use my service principal with the login action or should i simply run the cli command in a run block ?

**Comment by brunoscota** [comment]
same happening here.

**Comment by BALAGA-GAYATRI** [comment]
Hi Please use `--sdk-auth` as mentioned in the readme - https://github.com/Azure/login#configure-a-service-principal-with-a-secret which generated the credentials in the required format.
