### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by devops-hemant** [Azure/login#299]
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: azure/login@v1.4.3

**Comment by BALAGA-GAYATRI** [comment]
Hi @devops-hemant , we have already updated our action to use node16 https://github.com/Azure/login/blob/releases/v1/action.yml#L37
Please use `azure/login@v1` or `azure/login@v1.4.7` to get the latest version of the action. The one which you are using seems old and not having the latest changes. Please feel free to reopen this issue if you still face the problem

**Comment by devops-hemant** [comment]
okay thanks
