### ISSUE TITLE
Azure Login using same federated service principal succeeding on Github provided runner and failing on self-hosted runner

### ISSUE THREAD

**Issue by yadusum** [Azure/login#302]
I have a federated service principal attached with github repo. Azure login succeeds on ubuntu-latest runner, but same azure login task fails when self-hosted github runner is used with following error:

Using OIDC authentication...
Error:  Cannot read properties of undefined (reading 'message'). Please make sure to give write permissions to id-token in the workflow.
/bin/az cloud set -n azurecloud
Done setting cloud: "azurecloud"
Error: : AADSTS50027: JWT token is invalid or malformed.
Trace ID: xxxxxxxx-xxxx(https://github.com/xxxxx/xxxxx/actions/runs/xxxxx/jobs/xxxxx#step:x:xx)x-xxxx-xxxx-xxx[xx](https://github.com/xxxx/xxxxx/actions/runs/xxxxxxxxxx/jobs/xxxxxx#step:x:xx)xxxxxxx
Correlation ID: xxxxx
Timestamp: xxxx

Error: To re-authenticate, please run:
az login

Error: Az CLI Login failed. Please check the credentials and make sure az is installed on the runner. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows

**Comment by BALAGA-GAYATRI** [comment]
Please make sure to provide the below permissions in your workflow- 
```
permissions:
      id-token: write
      contents: read
```
Can you share your workflow for more details if the above suggestion didn't help.

**Comment by yadusum** [comment]
The below permissions are in place at workflow level:
permissions:
      id-token: write
      contents: read

**Comment by yadusum** [comment]
The issue is still there, the flow is as follows:

name: 'CallTestAzureLoginIssue'

# Controls when the workflow will run
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  deploy:
    runs-on: runner2
    environment: dev

    steps:

    - name: 'Echo ID token'
      run: |
        az version
        echo "ACTIONS_ID_TOKEN_REQUEST_URL = $ACTIONS_ID_TOKEN_REQUEST_URL"
        echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN = $ACTIONS_ID_TOKEN_REQUEST_TOKEN"

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          audience: 'api://AzureADTokenExchange'

**Comment by yadusum** [comment]
> Please make sure to provide the below permissions in your workflow-
> 
> ```
> permissions:
>       id-token: write
>       contents: read
> ```
> 
> Can you share your workflow for more details if the above suggestion didn't help.

name: 'CallTestAzureLoginIssue'

# Controls when the workflow will run
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  deploy:
    runs-on: runner2
    environment: dev

    steps:

    - name: 'Echo ID token'
      run: |
        az version
        echo "ACTIONS_ID_TOKEN_REQUEST_URL = $ACTIONS_ID_TOKEN_REQUEST_URL"
        echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN = $ACTIONS_ID_TOKEN_REQUEST_TOKEN"

    - name: 'Login to Azure'
      uses: azure/login@v1.4.5
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          audience: 'api://AzureADTokenExchange'

**Comment by BALAGA-GAYATRI** [comment]
Thanks for sharing your workflow. A quick check to understand if you have setup the federated credential for the `environment` that you are using.

**Comment by yadusum** [comment]
> Thanks for sharing your workflow. A quick check to understand if you have setup the federated credential for the `environment` that you are using.

Actually the federated credential is setup. The azure login using azure/login@v1 works fine when the runner is set to below:
deploy:
  runs-on: ubuntu-latest
  environment: dev

But the azure login using azure/login@v1 fails when the runner is set to self-hosted:
deploy:
  runs-on: runner2
  environment: dev

I also ran the ./run.sh --check --url <repo name> --pat <pat> to troubleshoot if self hosted runner has any issues:

But all checks w.r.t reaching api.github.com and other github urls are all passed

**Comment by lpellegr** [comment]
Same issue using credentials. All work on Github hosted runners but fails on self-hosted runners!

**Comment by lpellegr** [comment]
@yadusum Did you check if the node running your self-hosted runner has `az` and `kubectl`  commands installed? this was the issue on my side. 

On ubuntu, you can install `az` as follows:

```
sudo apt-get install azure-cli
```

for `kubectl`:

https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/

**Comment by AguangMikeZhang** [comment]
I am having the same issue. Everything works on github runners but not on self-hosted docker runners. The self-hosted runner has Azure CLI and kubectl installed.

**Comment by jku-sr** [comment]
same, i've also attempted this as well before azure/login

`      - name: Install Azure cli
        run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli
          az --version`

**Comment by gilles-gosuin** [comment]
@BALAGA-GAYATRI Any update on this? This is a major showstopper, as there basically is no proper Github <> Azure integration, with self-hosted runners running inside Azure itself... Quite the irony!

First step would probably be to remove the "Question" label and add the "Bug" label... or explain to us how to use OIDC with self-hosted runners (ie. answer the "question"). It's pretty clear most of us here have installed the Azure CLI on the runner. 

Adding meaningful logging and debugging options to the script might be useful as well as this error only generates a useless generic message from a (too long) try/catch block.

**Comment by ruqaiyah-oqc** [comment]
> @BALAGA-GAYATRI Any update on this? This is a major showstopper, as there basically is no proper Github <> Azure integration, with self-hosted runners running inside Azure itself... Quite the irony!
> 
> First step would probably be to remove the "Question" label and add the "Bug" label... or explain to us how to use OIDC with self-hosted runners (ie. answer the "question"). It's pretty clear most of us here have installed the Azure CLI on the runner.
> 
> Adding meaningful logging and debugging options to the script might be useful as well as this error only generates a useless generic message from a (too long) try/catch block.

use this before running action

ensure:
`id-token: write` is enabled 
``````
- name: az cli install
      run: |
            sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
            curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
            AZ_REPO=$(lsb_release -cs)
            echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
            sudo apt-get update
            sudo apt-get install azure-cli
            # Update the list of packages
            sudo apt-get update
            # Install pre-requisite packages.
            sudo apt-get install -y wget apt-transport-https software-properties-common
            # Download the Microsoft repository GPG keys
            wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
            # Register the Microsoft repository GPG keys
            sudo dpkg -i packages-microsoft-prod.deb
            # Delete the the Microsoft repository GPG keys file 
            rm packages-microsoft-prod.deb
            # Update the list of packages after we added packages.microsoft.com
            sudo apt-get update
            # Install PowerShell
            sudo apt-get install -y powershell -f
```

**Comment by jku-sr** [comment]
> same, i've also attempted this as well before azure/login
> 
> ```
>       - name: Install Azure cli
>         run: |
>           sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
>           curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
>           AZ_REPO=$(lsb_release -cs)
>           echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
>           sudo apt-get update
>           sudo apt-get install azure-cli
>           az --version
> ```
> 
> AZ version will list, but the next step when performing azure/login results in the same error as others
> 
> Please check the credentials and make sure az is installed on the runner. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows

Following up on this. It appears we cannot run the AZ Cli install as part of the workflow since it only installs it for that session, the second you go to the next step for Azure/Login the container is cleaned up and the AZ CLI is lost. 

My only work around is to manually go to my Self-Hosted runner and install AZ CLI on the virtual machine itself, so the AZ Cli is available for any container that github actions launches.

**Comment by AguangMikeZhang** [comment]
> > @BALAGA-GAYATRI Any update on this? This is a major showstopper, as there basically is no proper Github <> Azure integration, with self-hosted runners running inside Azure itself... Quite the irony!
> > First step would probably be to remove the "Question" label and add the "Bug" label... or explain to us how to use OIDC with self-hosted runners (ie. answer the "question"). It's pretty clear most of us here have installed the Azure CLI on the runner.
> > Adding meaningful logging and debugging options to the script might be useful as well as this error only generates a useless generic message from a (too long) try/catch block.
> 
> use this before running action
> 
> ensure: `id-token: write` is enabled
> 
> ```
> - name: az cli install
>       run: |
>             sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
>             curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
>             AZ_REPO=$(lsb_release -cs)
>             echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
>             sudo apt-get update
>             sudo apt-get install azure-cli
>             # Update the list of packages
>             sudo apt-get update
>             # Install pre-requisite packages.
>             sudo apt-get install -y wget apt-transport-https software-properties-common
>             # Download the Microsoft repository GPG keys
>             wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
>             # Register the Microsoft repository GPG keys
>             sudo dpkg -i packages-microsoft-prod.deb
>             # Delete the the Microsoft repository GPG keys file 
>             rm packages-microsoft-prod.deb
>             # Update the list of packages after we added packages.microsoft.com
>             sudo apt-get update
>             # Install PowerShell
>             sudo apt-get install -y powershell -f
> ```
> ```

Thanks for the response. I had both az-cli and powershell installed inside the self-hosted docker runner but I still get that error.

**Comment by gilles-gosuin** [comment]
@ruqaiyah-oqc Please, stop telling us to install the Azure CLI. We know it's needed, it's been told several times above, it IS installed. This is not the issue here.

> Following up on this. It appears we cannot run the AZ Cli install as part of the workflow since it only installs it for that step, the second you go to the next step for Azure/Login the container is cleaned up and the AZ CLI install is lost.

@jku-sr What container are you referring to? Everything that is installed using apt-get will end up being available to all users on the runner host and will remain available until it is explicitly uninstalled. Unless of course you are using ephemeral runners on Azure Container Apps or whatever, in which case you should of course install it in your runner image. Anyway, steps of a given job are all executed on the same runner, so your remark does not apply either way.

**Comment by gilles-gosuin** [comment]
Turns out my problem was that the user running the runner service was missing a home directory, which made the Azure CLI fail with a very explicit error message... that was swallowed by the login script.

My suggestion above still stands : please give users a means of debugging what's going on exactly when it fails, it will probably prevent many bug reports from being created.

**Comment by jku-sr** [comment]
> 

in reference to the container I have this output the end of my Run command step:

```
az script ran successfully.
cleaning up container...
```

To me that means it installed AZ CLI only in that container and it was then cleanedup/deleted, on my next step when I try to do azure/login I get the 

`"Error: Az CLI Login failed. Please check the credentials and make sure az is installed on the runner. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows"`

I don't know why but i had to manually install az cli at the OS level on my linux runner. Hope that makes sense

**Comment by MoChilia** [comment]
Hi @yadusum,
Are you still experiencing the [AADSTS50027: InvalidJwtToken](https://learn.microsoft.com/en-us/azure/active-directory/develop/reference-aadsts-error-codes#:~:text=access%20this%20tenant.-,AADSTS50027,-InvalidJwtToken%20%2D%20Invalid%20JWT) error? I've investigated the issue and found some potential solutions:

1. Ensure that you're using the latest version of `az cli`.
2. Make sure that the clock on your self-hosted runner is synced with the Azure AD servers.
3. Double-check that your federated credential is valid and has the necessary permissions to perform the action.

If the issue persists, please use the debug branch with `uses: azure/login@debug` in your workflow to output more information. This will help us better troubleshoot the issue.

**Comment by MoChilia** [comment]
Hi @jku-sr,
Are you using the `azure/cli` action? This action will not install `az cli` on your runner, since it runs on the docker container with preinstalled `az cli`. Once you finish the `azure/cli` action, it will clean up the container. You should install `az cli` on your runner before using `azure/login` with command like 
```
curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
```
BTW, don't use `azure/cli` before `azure/login`. The standard operation to run any Azure actions is to perform the login action first.

**Comment by jku-sr** [comment]
> Hi @jku-sr, Are you using the `azure/cli` action? This action will not install `az cli` on your runner, since it runs on the docker container with preinstalled `az cli`. Once you finish the `azure/cli` action, it will clean up the container. You should install `az cli` on your runner before using `azure/login` with command like
> 
> ```
> curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
> ```
> 
> BTW, don't use `azure/cli` before `azure/login`. The standard operation to run any Azure actions is to perform the login action first.

Hi @MoChilia 

You are correct, i am not running Azure/CLI action since I realized it's a docker container that gets cleaned up after the step is done. I have a separate run step now that installs AZ CLI at the Runner OS level before using azure/login

**Comment by Z4ck404** [comment]
Hey, 
Any updates on this issue ? 
it's really strange that it works on GitHub hosted runners and not on self-hosted ones.

**Comment by YanaXu** [comment]
Hi @Z4ck404 , the PR is merged and we'll release it this Month. 
If it blocks you somehow, you can use a workaround solution like https://github.com/Azure/login/issues/340#issuecomment-1624796136. And you can refer to the guide https://github.com/Azure/login/blob/6fd41fcee35d23a9aa03460fab8bb9f94fad4e0b/README.md#login-with-system-assigned-managed-identity .

**Comment by Z4ck404** [comment]
> Hi @Z4ck404 , the PR is merged and we'll release it this Month. If it blocks you somehow, you can use a workaround solution like [#340 (comment)](https://github.com/Azure/login/issues/340#issuecomment-1624796136). And you can refer to the guide https://github.com/Azure/login/blob/6fd41fcee35d23a9aa03460fab8bb9f94fad4e0b/README.md#login-with-system-assigned-managed-identity .

Thanks a lot for your reply @YanaXu. I think I can wait for the release if it will happen soon

**Comment by cveld** [comment]
@YanaXu I am bit confused as the OP requests for guidance on federated login whereas you point to a paragraph about system assigned managed identity login. Can you elaborate on this a bit?

**Comment by YanaXu** [comment]
> @YanaXu I am bit confused as the OP requests for guidance on federated login whereas you point to a paragraph about system assigned managed identity login. Can you elaborate on this a bit?

Hi @cveld, the last comment is not valid anymore since the self-hosted runners now is supported in `v1`. 
In my last comment, since it's not supported yet, I suggest users to use System Managed Identity to login for a workaround. 
But now since they are all supported, please refer to the guide and choose a best login method for your cases.

- [Login With OpenID Connect (OIDC) [Recommended]](https://github.com/Azure/login/blob/master/README.md#login-with-openid-connect-oidc-recommended)
- [Login With a Service Principal Secret](https://github.com/Azure/login/blob/master/README.md#login-with-a-service-principal-secret)
- [Login With System-assigned Managed Identity](https://github.com/Azure/login/blob/master/README.md#login-with-system-assigned-managed-identity)
- [Login With User-assigned Managed Identity](https://github.com/Azure/login/blob/master/README.md#login-with-user-assigned-managed-identity)

**Comment by YanaXu** [comment]
I'll close this issue since it's solved now.
