### ISSUE TITLE
SECURITY: Azure/login in some cases leaks Azure Application Variables to the GitHub build log

### ISSUE THREAD

**Issue by NoCopy** [Azure/login#315]
As per the title. 

Running a command such as:

```
- name: 'Configure Deployment Target'
  run: az webapp config appsettings set --name <NAME> --resource-group <RG> --settings DEPLOYMENT_TARGET=<TARGET>
```

Results in a returned result of:

```
[
  ***
    "name": "MY_SUPER_SECRET_APP_SETTING",
    "value": "<some SUPER_SECRET ENV var from Azure Key Store>
  ***,
  ***
    "name": "APPINSIGHTS_INSTRUMENTATIONKEY",
    "value": "<some value>
  ***,
```
Since the AZ CLI is by default assumed be running / logging in a secure environment I understand some commands are going to output this information but they should not be carried over to the git hub log. 

I would recommend some additional settings:

```
uses: azure/login@v1
  with:
    creds: ${{ secrets.AZURE_CREDENTIALS }}
    git_log: true    # default false
    
    OR
    
    azure_log: true
    blob: ${{ secrets.BLOB_CREDENTIALS }} / PATH 
```

**Comment by MoChilia** [comment]
Hi @NoCopy! If you don't want to show the output of `az cli` commands, you can try the option `-o None`.

**Comment by NoCopy** [comment]
@MoChilia Yes, I am aware of that. However that is a dangerous thing to rely on. Out of a pool of say 100 devs, I bet 70% are not aware of that setting - especially since it not even in the docs of this repo as a warning. Of that 30% that are aware another 50% of those are probably going to forget, make a typo, or remember when it is an issue - or just see it, like I did. I would have never expected to be leaking ENV vars to the log if my build didn't fail initially. Had it worked, I would have probably never noticed it.

In that respect, I HIGHLY suspect MANY repos are leaking ENV vars that they are not aware of. This is an issue that should be taken seriously. Defaulting to no logs would be the safest, and at the very least this repo should update the readme with a very strict security warning at the top (not way down below) to warn users of this potential pitfall.

**Comment by MoChilia** [comment]
@NoCopy, this action won't pass any account information or ENV vars to the GitHub log. The command you mentioned is not within the scope of login action. Nevertheless, I appreciate your suggestion and I believe it deserves attention.  I will record it as an improvement for the azure/cli action and discuss the design within the team. Thanks!

**Comment by MoChilia** [comment]
@NoCopy, the scope of login action is within the step
```yaml
-name: Run Azure Login
     uses: azure/login@v1
     with: xxx
```
Once you finished the login action, it is difficult to handle the users' behavior in the following steps, since other Azure actions may have their own method to control the output. 

And I want to clarify that the login action does **not** pass any console output to the GitHub log. All of the outputs are prompts without any confidential Information, like
```
/usr/bin/az cloud set -n azurecloud
Done setting cloud: "azurecloud"
Note: Azure/login action also supports OIDC login mechanism. Refer https://github.com/azure/login#configure-a-service-principal-with-a-federated-credential-to-use-oidc-based-authentication for more details.
Login successful.
```
