### ISSUE TITLE
v1.4.5 was a breaking change for GitHub Self-Hosted Runner users

### ISSUE THREAD

**Issue by cperfect** [Azure/login#325]
We have just been hit by this issue https://github.com/docker/login-action/issues/159 using this action via the version "v1" on Self Hosted runners: The [v1.4.5 release](https://github.com/Azure/login/releases/tag/v1.4.5) includes the note "Also upgraded the Node version to 16.". 

While we can upgrade our self hosted runners to fix this surely this is a breaking change and, assuming semantic versioning, this should require a major version increment?

**Comment by YanaXu** [comment]
Hi @cperfect , I'm closing this issue since it's idle for a few months. Feel free to reopen it if necessary and please provide the information.
