### ISSUE TITLE
Patch Github workflows using set-output

### ISSUE THREAD

**Issue by cloudsky13** [Azure/login#327]
Hi Team,

Since GitHub Actions is deprecating save-state and set-output commands [link](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) from 31st May 2023, we must update any workflows using the old syntax.

I found these two occurrences in the azure/login repository, 
[one](https://github.com/Azure/login/blob/990b22f2bceb30f6bb94f1713b46a0be2c707d93/.github/workflows/azure-login-integration-tests.yml#L125)
[two](https://github.com/Azure/login/blob/master/.github/workflows/azure-login-canary.yml#L90)

Not aware of the impact and use cases of above workflows, but since these are run frequently one must update these to the new syntax provided in the link.

**Comment by cloudsky13** [comment]
Hi Team, I'm aware it's a minor change and would like to take this opportunity to help with this, if possible. Since I'm new to open source, I'm not aware if can be assigned this issue or not. can someone please clarify that? Thanks.

**Comment by YanaXu** [comment]
Hi @cloudsky13 ,

Thanks for helping to point it out. 
We're recently fixing these workflows since they have been broken for a while.
We're happy if you want to contribute to Azure Login Action. If you want to contribute some features, you can create a pull request to this repo and provide the necessary tests towards Azure.

**Comment by YanaXu** [comment]
I'll close this issue since it's answered. Feel free to open a new one if you have other questions. Feel free to create a Pull Request if you want to contribute to Azure Login Action. Thanks.
