### ISSUE TITLE
Azure Login getting failed

### ISSUE THREAD

**Issue by Saikiran-R** [Azure/login#337]
Hello Team,

I have the following workflow : 

name: build and push to WebApp
on: push

jobs:
  build-and-deploy-WebApp:
    runs-on: [self-hosted]
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

 

    - name: Install Azure cli
      run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli

    - name: show az version
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az version
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.SPN_CLIENT_ID }}","clientSecret":"${{ secrets.SPN_CLIENT_SECRET }}","tenantId":"${{ secrets.TENANT_ID }}"}'

 I have added the organization secret for client ID and secret. but I am getting this error  : Run azure/login@v1
  with:
    creds: {"clientId":"***","clientSecret":"***","tenantId":"***"}
    enable-AzPSSession: false
    environment: azurecloud
    allow-no-subscriptions: false
    audience: api://AzureADTokenExchange
Error: Az CLI Login failed. Please check the credentials and make sure az is installed on the runner. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows

**Comment by Saikiran-R** [comment]
There is no issue while installing the cli, and we have received confirmation from internal team that the credentials are correct could you please help us in resolving the issue.

**Comment by MoChilia** [comment]
Duplicated of https://github.com/Azure/login/issues/306.

Please don't run `azure/cli` before `azure/login`, the standard operation to run any Azure actions is to perform the login action first.

**Comment by Saikiran-R** [comment]
Hello MoChilia,

I have removed Azure/cli but the result is same. Please refer to new workflow :

name: build and push
on: push

jobs:
  build-and-deploy-WebApp:
    runs-on: [self-hosted]
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

 

    - name: Install Azure cli
      run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.SPN_CLIENT_ID }}","clientSecret":"${{ secrets.SPN_CLIENT_SECRET }}","tenantId":"${{ secrets.TENANT_ID }}"}'

Thanks and Regards,
Saikiran

**Comment by MoChilia** [comment]
Hi @Saikiran-R, 
There are some problems in the shared workflow.
1. You should either pass the `subscription-id`or set `allow-no-subscriptions` to true. Both of these parameters are missing in the shared workflow.
2. It seems that the credentials were not passed correctly. The error message indicates that the value of  `clientId` and `clientSecret` were not provided. Please verify that the secrets `SPN_CLIENT_ID` and `SPN_CLIENT_SECRET` are valid and correctly stored in your GitHub repo.
3. As an additional precaution, please check if Azure CLI was successfully installed on your self-hosted runner. You can verify this by checking the debug log of the azure/login action or by adding a step `- run: az --version` before the login action.

**Comment by jacob7395** [comment]
Hey, I believe I'm getting the same issue.

```
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
    - name: Login to ACR
      run: |
        az acr login --name $ACR_NAME
```

I get an error saying it cant find the subscription.

If I set allow-no-subscriptions on the login step it passes but then the acr login fails with the same error.

My credentials are set using terraform, and I have validated the sub id multiple time, to check I entered all the credential manly and get the same error.

**Comment by MoChilia** [comment]
Closing this issue for now. If you have any further questions, please feel free to reopen it.
