### ISSUE TITLE
unable to login in to azure by using Azue Login github action

### ISSUE THREAD

**Issue by AIopsGeek** [Azure/login#339]
Expected Behaviour
It should login in to Azure cloud from Github Actons CI. Tried by recreating the secrets manually and also through az cli but still getting the same error.

Actual Behaviour
getting error

Error: Az CLI Login failed. Please check the credentials and make sure az is installed on the runner. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows

Terraform Configuration Files
on:
  workflow_call:
jobs:
  build-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.path }}
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        
      - name: Set up Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

Debug Output/Panic Output
3s
##[debug]Evaluating condition for step: 'Set up Azure login'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Set up Azure login
##[debug]Loading inputs
##[debug]Evaluating: secrets.AZURE_CREDENTIALS
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'AZURE_CREDENTIALS'
##[debug]=> null
##[debug]Result: null
##[debug]Loading env
Run azure/login@v1
##[debug]=> null
##[debug]Result: null
##[debug]Loading env
Run azure/login@v1
##[debug]az cli version used: /usr/bin/az
##[debug]az cli version used:
##[debug]azure-cli                         2.49.0
##[debug]
##[debug]core                              2.49.0
##[debug]telemetry                          1.0.8
##[debug]
##[debug]Extensions:
##[debug]azure-devops                      0.26.0
##[debug]
##[debug]Dependencies:
##[debug]msal                              1.20.0
##[debug]azure-mgmt-resource               22.0.0
##[debug]
##[debug]Python location '/opt/az/bin/python3'
##[debug]Extensions directory '/opt/az/azcliextensions'
##[debug]
##[debug]Python (Linux) 3.10.10 (main, May 19 2023, 08:20:31) [GCC 11.3.0]
##[debug]
##[debug]Legal docs and information: aka.ms/AzureCliLegal
##[debug]
##[debug]
##[debug]Your CLI is up-to-date.
##[debug]
Error: Az CLI Login failed. Please check the credentials and make sure az is installed on the runner. For more informatio

**Comment by MoChilia** [comment]
Hi @AIopsGeek,
As it shown in the debug information, the input `secrets.AZURE_CREDENTIALS` was not passed successfully to the workflow.
```
##[debug]..=> 'AZURE_CREDENTIALS'
##[debug]=> null
```
Please make sure the secret is truly stored in your GitHub repository. And this can also occur when the workflow is triggered by a pull request from a forked repository. Please verify if this is the case for you. If it is, then you should also add the credential to the forked repo.

**Comment by MoChilia** [comment]
Closing this issue for now. If you have any further questions, please feel free to reopen it.
