### ISSUE TITLE
Failed every time SP has "special" character. 

### ISSUE THREAD

**Issue by Mikhail2k15** [Azure/login#34]
Login via Az module2m 32s
##[error]Error: The process '/usr/bin/pwsh' failed with exit code 1
        return ConvertTo-Json $output
***
  "Success": "true",
  "AzVersion": "1.7.5"
***
/usr/bin/pwsh -Command try ***
            $ErrorActionPreference = "Stop"
            $WarningPreference = "SilentlyContinue"
            $output = @***
            Clear-AzContext -Scope Process;
             Clear-AzContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue;Connect-AzAccount -ServicePrincipal -Tenant 72f988bf-86f1-41af-91ab-2d7cd011db47 -Credential             (New-Object System.Management.Automation.PSCredential('36f6d11b-d43f-46ee-a8e6-1e814352d0d1',(ConvertTo-SecureString *** -AsPlainText -Force)))                 -Environment AzureCloud | out-null;Set-AzContext -SubscriptionId aebd2f6a-2339-4659-ae8c-f5eeeb4f94dd -TenantId 72f988bf-86f1-41af-91ab-2d7cd011db47 | out-null;
            $output['Success'] = "true"
        ***
        catch ***
            $output['Error'] = $_.exception.Message
        ***
        return ConvertTo-Json $output
ParserError: 
Line |
   6 |  … 14352d0d1',(ConvertTo-SecureString qSIm=%Qut0~8.`.!xsh:)aT+i#;Dafk] - …
     |                                                            ~~~~~
     | Unexpected token 'aT+i#' in expression or statement.

##[error]Azure PowerShell Login failed. Please check the credentials. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows"

**Comment by aksm-ms** [comment]
Issue is fixed in PR.
