### ISSUE TITLE
Enterprise Usage Issues

### ISSUE THREAD

**Issue by richardreyes** [Azure/login#340]
Hello,

We are using this action without issues inside our enterprise repositories until we were advised that we are prohibited from using actions in the marketplace for security reasons. My initial thought was to clone a copy of this repo inside our enterprise repo but I cannot find any documentation on how to use the Azure/login action after having it cloned.

Is making a copy inside our enterprise repo a correct approach?

Is there a better way?

Thank you in advance.

**Comment by YanaXu** [comment]
Hi @richardreyes ,

Have you tried [Enabling automatic access to GitHub.com actions using GitHub Connect](https://docs.github.com/en/enterprise-server@3.9/admin/github-actions/managing-access-to-actions-from-githubcom/enabling-automatic-access-to-githubcom-actions-using-github-connect)?

Below is the recommendation from GitHub.

------
GitHub Actions on GitHub Enterprise Server is designed to work in environments without full internet access. By default, workflows cannot use actions from GitHub.com and [GitHub Marketplace](https://github.com/marketplace?type=actions).

The recommended approach of enabling access to actions from GitHub.com is to enable automatic access to all actions. You can do this by using GitHub Connect to integrate GitHub Enterprise Server with GitHub Enterprise Cloud. For more information, see "[Enabling automatic access to GitHub.com actions using GitHub Connect](https://docs.github.com/en/enterprise-server@3.9/admin/github-actions/managing-access-to-actions-from-githubcom/enabling-automatic-access-to-githubcom-actions-using-github-connect)."

However, if you want stricter control over which actions are allowed in your enterprise, you can follow this guide to use GitHub's open source [actions-sync](https://github.com/actions/actions-sync) tool to sync individual action repositories from GitHub.com to your enterprise.

**Comment by richardreyes** [comment]
Hi @YanaX,

Both of the repo is now inside our enterprise git. Repo A is where our custom WF resides while Repo B is a clone of Azure/Login. 

What I am missing is how to call 

 uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

using the repo B/azure_login action.

I keep ending to this article though:

https://dev.to/n3wt0n/finally-custom-github-actions-in-internal-repos-4l91

I am making my way into trying it but this involves a different team so its a bit slow

I hoping there is an easier way.

Thank you again!

-Richard

**Comment by YanaXu** [comment]
Hi @richardreyes ,

We suggest you use GitHub Actions from Marketplace like this: [Enabling automatic access to GitHub.com actions using GitHub Connect](https://docs.github.com/en/enterprise-server@3.9/admin/github-actions/managing-access-to-actions-from-githubcom/enabling-automatic-access-to-githubcom-actions-using-github-connect)?
But if you insist on a forked enterprise repo, please follow [Manually syncing actions from GitHub.com](https://docs.github.com/en/enterprise-server@3.9/admin/github-actions/managing-access-to-actions-from-githubcom/manually-syncing-actions-from-githubcom) to sync the repo.
Here is the information for using a fork repo:

- Azure Login Action is a type script action. You can follow [Creating a JavaScript action](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action) to build it or maintain it.
- If you want to use it in your workflow, follow this page: [Adding an action from GitHub Marketplace](https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#adding-an-action-from-github-marketplace).

For example, if you fork repo full name is **Your_Enterprise/login**, here is one way to use it in GitHub Workflow:

- clone the fork repo
- checkout to a new branch based on the master branch
  - git checkout -b <your_branch>
- build it with npm
  - npm install
  - npm run build
  - npm run test
- commit all installed node modules and built lib
  - git add -f .\node_modules\
  - git add -f lib
  - git commit -m "add installed node modules and built lib"
- push the new branch to your fork repo
  - git push --set-upstream origin <your_branch>
- Now you can use the built branch in your workflow
  - uses: Your_Enterprise/login@your_branch

Just as a reminder, a fork repo is out of the scope of our support.

**Comment by richardreyes** [comment]
Thank you @YanaXu. I will try the steps above and update this post.
