### ISSUE TITLE
Very slow login with federated credentials on GitHub Hosted Windows Runners 

### ISSUE THREAD

**Issue by spacentropy** [Azure/login#345]
Hello. We observe very slow login speeds when using [federated credentials](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure) on windows-latest runner.
Currently login takes 2-3 mins which is very slow for this kind of operation. Can we do something to speed this up?

**Comment by MoChilia** [comment]
Closing this issue for now. Please review the provided solution above. If you continue to encounter this issue, kindly share your settings and workflow details so that we can identify the root cause.
