### ISSUE TITLE
AZURE_SUBSCRIPTION_ID should not be a secret

### ISSUE THREAD

**Issue by franpb90** [Azure/login#347]
In my opinion, the Subscription ID should not be considered a secret. I think it is important to write in the logs what subscription have been modified.

The moment a workflow calls to this action, it considers this value as a secret, replacing the value in logs and avoiding passing the id of a resource as output from one job to another (because the subscription_id is part of the resource_id and it is considered a secret)

**Comment by YanaXu** [comment]
Hi @franpb90 , I do not understand your question.
Do you mean this configuration?
```json
subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
```

You can write your workflow like this (use plain text instead of secrets).
```
subscription-id: XXXXXXXXXXXXXXX
```

It's up to you. But we suggest to use secrets.

**Comment by franpb90** [comment]
Hi Yan Xu,

I have tested using ${{ vars.AZURE_SUBSCRIPTION_ID }} as part of *creds. *The
workflow considered vars.AZURE_SUBSCRIPTION_ID as secret after
***@***.*** step. I will test it by passing it as a *subscription-id*.

**Comment by YanaXu** [comment]
I've tested it and it seems GitHub automatically masking the subscription id. 
I'll close this issue since it's by design of GitHub.
