### ISSUE TITLE
azure/login@v1 does not work on MacOS runners

### ISSUE THREAD

**Issue by ilia-shipitsin** [Azure/login#351]
Hello,

we are trying to use [OIDC Federation](https://learn.microsoft.com/en-us/azure/active-directory/workload-identities/workload-identity-federation-create-trust)

it works for Windows, Ubuntu, but does not work for macos-11, macos-12, macos-13.

I created small [repro](https://github.com/ilia-shipitsin/azure-login-macos/actions/runs/6417829831)

**Comment by ilia-shipitsin** [comment]
![image](https://github.com/Azure/login/assets/125650415/282eb95c-b226-4799-8082-7c8812f9a6fa)

**Comment by YanaXu** [comment]
Hi @ilia-shipitsin , yes, it's a known limitation in Azure Login Action. This will be fixed in https://github.com/Azure/login/pull/348.

**Comment by YanaXu** [comment]
It depends on Azure PowerShell installed on GitHub Action runners. You can check the source code for details. It's in [login/src/PowerShell/Utilities/Utils.ts Line 27](https://github.com/Azure/login/blob/5906929b67adab884c91d130ce6a7a3a4205a8dd/src/PowerShell/Utilities/Utils.ts#L27C20-L27C20) .

**Comment by ilia-shipitsin** [comment]
@yanaxu, did you check a link to the repro provided ?

it does not have "OS not supported".
it beleives OS is supported


![image](https://github.com/Azure/login/assets/125650415/e26d28bf-e0ee-4d1a-8de1-7901b5b58b37)

**Comment by YanaXu** [comment]
Hi @ilia-shipitsin , it's because "v1" is an old version of source code. Please check the [code ](https://github.com/Azure/login/blob/92a5484dfaf04ca78a94597f4f19fea633851fa2/src/main.ts#L215C15-L215C15). The reason is still same.

**Comment by ilia-shipitsin** [comment]
@yanaxu, I forked repo, tagged your branch as "v2", it complains that cannot find a file

![image](https://github.com/Azure/login/assets/125650415/d2e0f1a5-1337-4b78-afc0-61aad063b3f9)

do you have ETA for new release ?

**Comment by ilia-shipitsin** [comment]
@yanaxu, do you have any estimation of new release ?

**Comment by YanaXu** [comment]
Hi @ilia-shipitsin , we're planning to release it next Month. If you want to try your fork repo, please try the steps [here](https://github.com/Azure/login/issues/340#issuecomment-1624796136).

**Comment by ilia-shipitsin** [comment]
I've just tested on v1.5.0, everything works.
thank you!
