### ISSUE TITLE
Login via Azure CLI  check the credentials

### ISSUE THREAD

**Issue by AdieOlami** [Azure/login#354]
Hi, so I had my pipeline working before then I canceled my GitHub Enterprise subscription and suddenly it stopped working and I get this error when I run my GitHub action

```
- name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS_NEW }}
```

I have AZURE_CREDENTIALS_NEW stored in my organization secrets and it worked before but now it just would not work. I have tried another `az ad sp create-for-rbac` and tried with the new credentials but the issue remains the same. 

Any help is appreciated 

> Run azure/login@v1
>   with:
>     creds: ***
>     enable-AzPSSession: false
>     environment: azurecloud
>     allow-no-subscriptions: false
>     audience: api://AzureADTokenExchange
>   env:
>     GITHUB_PAGES_REPO: xxx/helm-charts
>     GITHUB_PAGES_BRANCH: gh-pages
>     HELM_VERSION: 3.8.1
>     ACR_NAME: ***
> /usr/bin/docker exec  xxx sh -c "cat /etc/*release | grep ^ID"
> Error: Az CLI Login failed. Please check the credentials and make sure az is installed on the runner. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows

LOGS

```
##[debug]Evaluating condition for step: 'Login via Azure CLI'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Login via Azure CLI
##[debug]Loading inputs
##[debug]Evaluating: secrets.AZURE_CREDENTIALS_NEW
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'AZURE_CREDENTIALS_NEW'
##[debug]=> '***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]***'
##[debug]Result: '***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]  ***
##[debug]***'
##[debug]Loading env
Run azure/login@v1
  with:
    creds: ***
    enable-AzPSSession: false
    environment: azurecloud
    allow-no-subscriptions: false
    audience: api://AzureADTokenExchange
  env:
    GITHUB_PAGES_REPO: xxx/helm-charts
    GITHUB_PAGES_BRANCH: gh-pages
    HELM_VERSION: 3.8.1
    ACR_NAME: ***
/usr/bin/docker exec  xxx sh -c "cat /etc/*release | grep ^ID"
##[debug]ID=alpine
##[debug]Container distribution is alpine. Running JavaScript Action with external tool: node16_alpine
Error: Az CLI Login failed. Please check the credentials and make sure az is installed on the runner. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows
##[debug]Node Action run completed with exit code 1
##[debug]AZURE_HTTP_USER_AGENT='GITHUBACTIONS/AzureLogin@v1_xxx/xxxxx-charts'
##[debug]AZUREPS_HOST_ENVIRONMENT='GITHUBACTIONS/AzureLogin@v1_xxx/xxxxx-charts'
##[debug]AZURE_HTTP_USER_AGENT=''
##[debug]AZUREPS_HOST_ENVIRONMENT=''
##[debug]Finishing: Login via Azure CLI
```

**Comment by MoChilia** [comment]
Hi @AdieOlami, sorry for the delay. Have you tried to run `az login` with your new credential locally? If it still doesn't work, please also include the local error message.

**Comment by MoChilia** [comment]
Closing the issue for now. If you have any further question, feel free to reopen it.
