### ISSUE TITLE
Deprecation warning due to Node 16

### ISSUE THREAD

**Issue by Piedone** [Azure/login#357]
Node 16 is [now deprecated](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). Because of this, when using this action, you'll see warnings.

Please update the action to Node 20.

**Comment by YanaXu** [comment]
Thanks @Piedone . We'll add it to our plan.

**Comment by Piedone** [comment]
Thank you!

**Comment by spkane** [comment]
cc/ @manidharanupoju24 (Another action that will need updating when a new Node 20 version is released).

**Comment by manuelpagliuca** [comment]
A new version will be released soon or just the current will be updated?

**Comment by ViktorDronov** [comment]
+

**Comment by onionhammer** [comment]
anyone maintaining this action?

**Comment by dbelyaev** [comment]
Please, prioritize this upgrade task. 

This action is used by tenth of thousands of different project, and deprecation has been announced in [09/2023](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/).

**Comment by FlorentATo** [comment]
@YanaXu can we prioritize this ? Thank you

**Comment by tjementum** [comment]
Would be great to get this solved. 🙏

**Comment by dcaro** [comment]
Thanks for the feedback and your patience, there are some challenges related to this that we need to solve as we address this issue. We will prioritize this work in our upcoming sprints and will report our ETA shortly.

**Comment by justinmchase** [comment]
I just want to point out that this is emitting warnings in everyones workflows...

![image](https://github.com/Azure/login/assets/10974/06cd3ea7-c0ac-4c3b-bcef-3892330cb973)

**Comment by justinmchase** [comment]
> ...there are some challenges related to this that we need to solve...

Can you elaborate @dcaro? Because it looks like its literally as simple as changing `node16` to `node20` in the action.yml file. I see there are already two PR's with this code change that you could probably merge in a couple minutes. But if you could elaborate on the concerns perhaps the pepople willing to do pull requests could address those changes?

It seems like just slapping a v2 onto it could help, no?

**Comment by jason-berk-k1x** [comment]
does anybody else see the irony in all this?

**Comment by tlchaffi** [comment]
Ran a test this morning to confirm this. I'm still getting a warning. Do we need to flip a version number or something?

**Comment by onionhammer** [comment]
Any ETA on release?

**Comment by YanaXu** [comment]
Hi @martincostello , @tlchaffi , @onionhammer , we're working on this and the PR is merged. Please wait for the release.

**Comment by ViktorDronov** [comment]
> Hi @martincostello , @tlchaffi , @onionhammer , we're working on this and the PR is merged. Please wait for the release.

is there any timeline for release?

**Comment by YanaXu** [comment]
Hi @ViktorDronov , we're testing it offline and working on the release date. It will happen soon. Please be patient for a few more days.
We didn't close this issue manually. It's closed because the related PR is merged. The issue's closure is automatically triggered by GitHub. Please be aware of this, if an issue is closed by a PR merge, it only works after a new release.

**Comment by tim-chaffin** [comment]
_Thread bump to make sure the issue doesn't go stale._

@YanaXu any update on the QA cycle, and an ETA?

**Comment by YanaXu** [comment]
Hi @tim-chaffin, we'll release it next week.

**Comment by tim-chaffin** [comment]
_Nudge_ @YanaXu 
Its been a few weeks now. Bumping this so its not forgotten. Any ETA?

**Comment by onionhammer** [comment]
It's out

**Comment by tim-chaffin** [comment]
Good call out @onionhammer , I didn't see the new tag.

For anyone who finds this issue, the fix was released here: https://github.com/Azure/login/releases/tag/v2.0.0
Syntax: `uses: azure/login@v2` to resolve.

**Comment by Piedone** [comment]
Perhaps you can nudge your colleagues here? https://github.com/Azure/webapps-deploy/issues/372
