### ISSUE TITLE
Package Size Issue with Azure Login GitHub Action

### ISSUE THREAD

**Issue by kWozniak-tt** [Azure/login#366]
## Description
I've identified a significant issue with the Azure login GitHub action, where the action's package size is excessively large. After unpacking, the node_modules directory alone is 118MB. This substantial size dramatically affects the startup time of the GitHub action. It seems all dependencies, including those not needed for production, are being installed in the package. Additionally, the package contains folders like __tests__, src, and .github, which are unnecessary for the action's operation.
![image](https://github.com/Azure/login/assets/70513945/ac2f231a-0657-4295-be8e-1e8302bcd82c)
![image](https://github.com/Azure/login/assets/70513945/bd0c17fc-420d-40eb-99fe-9572ef29a6fd)
[Download Link](https://codeload.github.com/Azure/login/legacy.tar.gz/92a5484dfaf04ca78a94597f4f19fea633851fa2)

## Proposed Solution:
1. **Production-Optimized Configuration**: Configure the package specifically for production use, adhering to npm standards. Exclude non-production dependencies and unnecessary folders like `__tests__`, `src`, and `.github` to reduce the package size and improve performance.
    
2. **Use of @vercel/ncc for Compiling Code**: As an alternative to checking in the `node_modules` directory, which can cause issues, use the `@vercel/ncc` tool to compile code and modules into a single file for distribution. This approach is suggested in [GitHub's documentation](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github). After installing `@vercel/ncc`, compile the `index.js` file, resulting in a new `dist/index.js` file with code and compiled modules, alongside a `dist/licenses.txt` file containing all licenses of the used `node_modules`. Update the `action.yml` file to use `dist/index.js` and remove the previously checked-in `node_modules` directory. This solution ensures a more efficient and streamlined package, in line with best practices for GitHub actions.

**Comment by kWozniak-tt** [comment]
I have created a pull request for the second solution:
https://github.com/Azure/login/pull/367
I also tested it in my repository

**Comment by jharbieh-microsoft** [comment]
Thanks for pointing this out and working on this case @kWozniak-tt

**Comment by YanaXu** [comment]
@kWozniak-tt, Thanks for raising this request. It's clear and helpful. We will add it to our plan.

**Comment by jharbieh-microsoft** [comment]
[heart]         Johnny Harbieh reacted to your message:
________________________________

**Comment by kWozniak-tt** [comment]
@MoChilia why this issue was unpinned

**Comment by YanaXu** [comment]
@kWozniak-tt no worries, we'll pin it again after this release. It's still on our table.
