### ISSUE TITLE
Post Action Cleanup

### ISSUE THREAD

**Issue by qoomon** [Azure/login#374]
From security perspective, it would be nice if you add a post action to cleanup credentials and logout alike to github action [aws-actions/configure-aws-credentials](
https://github.com/aws-actions/configure-aws-credentials/blob/cd299def7bdca014087ddce32aefb2380c6b6565/action.yml#L7)

**Comment by YanaXu** [comment]
@qoomon, thanks for your suggestion! Let's mark it as a feature and we'll add it to our plan.

**Comment by MoChilia** [comment]
Hi @qoomon,
The new version `v1.6.0` of azure/login has included the feature you requested. Use `azure/login@v1.6.0` to have a try. The pre-release announcement for `v1.6.0` can be found [here](https://github.com/Azure/login/issues/399). Any suggestions or feedback are welcome!

**Comment by qoomon** [comment]
thanks, LGTM
