### ISSUE TITLE
v1 commit is out of sync with the latest release version.

### ISSUE THREAD

**Issue by nuryupin-kr** [Azure/login#380]
Hi,
We are noticing that v1.5.0 and v1.5.1 are out, but v1 rolling tag still points to the same commit as 1.4.7. Is that intentional?
We are running into a scenario where we would like to use v1 rolling tag and have secrets with special characters which was fixed in v1.5.0.

**Comment by YanaXu** [comment]
Hi @nuryupin-kr , `v1` is moved to `v1.5.1` now. I'll close this issue. Feel free to open issues when you find problems.
