### ISSUE TITLE
OIDC Login failure

### ISSUE THREAD

**Issue by ManojNatarajanTR** [Azure/login#386]
I used OIDC Login enabling az-powershell session, but it fails with error

 Error: Azure PowerShell Login failed. Please check the credentials. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows"
Error: Error: Invalid AzPSVersion: 2.13.2

If I set enable-AzPSSession as false, OIDC login action works

**Comment by YanaXu** [comment]
Hi @ManojNatarajanTR ， could you provide your workflow file and the debug log?
