### ISSUE TITLE
Github is deprecating node16 on actions

### ISSUE THREAD

**Issue by eikooc** [Azure/login#391]
[Node 16 has reached End of Life (EoL)](https://nodejs.org/en/blog/announcements/nodejs16-eol)

Github supports node version 20 and we should move to use that instead

https://github.com/Azure/login/blob/45c3280904d6ab9d2fba45123b9e0aeb15ea9cd0/action.yml#L41

**Comment by YanaXu** [comment]
@eikooc thanks for your suggestion. You're right. And it's in our plan.

**Comment by YanaXu** [comment]
I'll close this issue since it's already tracked in #357.

**Comment by eikooc** [comment]
Sorry, I totally missed that. I've made a PR that updates the action https://github.com/Azure/login/pull/392
