### ISSUE TITLE
Website with the given name already exists

### ISSUE THREAD

**Issue by KiranKumarGowda** [Azure/login#395]
I want to deploy a standard logic app using github actions , for that i have created standard logic app  in different resource group and now i want to deploy this  logic app  using github actions , i'm getting error like this.

Error: ERROR: ***"status":"Failed","error":***"code":"DeploymentFailed","target":"/subscriptions/a4bd6d8e-cfd8-43c2-a63c-83a8c0ff91f1/resourceGroups/rg-dcs-cicr-centralindia-dev/providers/Microsoft.Resources/deployments/LA_Standard_Basic","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[***"code":"Conflict","target":"/subscriptions/a4bd6d8e-cfd8-43c2-a63c-83a8c0ff91f1/resourceGroups/rg-dcs-cicr-centralindia-dev/providers/Microsoft.Web/sites/Demo121","message":"***\r\n  \"Code\": \"Conflict\",\r\n  \"Message\": \"Website with given name Demo121 already exists.\",\r\n  \"Target\": null,\r\n  \"Details\": [\r\n    ***\r\n      \"Message\": \"Website with given name Demo121 already exists.\"\r\n    ***,\r\n    ***\r\n      \"Code\": \"Conflict\"\r\n    ***,\r\n    ***\r\n      \"ErrorEntity\": ***\r\n        \"ExtendedCode\": \"54001\",\r\n        \"MessageTemplate\": \"Website with given name ***0*** already exists.\",\r\n        \"Parameters\": [\r\n          \"Demo121\"\r\n        ],\r\n        \"Code\": \"Conflict\",\r\n        \"Message\": \"Website with given name Demo121 already exists.\"\r\n      ***\r\n    ***\r\n  ],\r\n  \"Innererror\": null\r\n***"***]***

Error: Deployment failed.
@YanaXu 

Can anyone help me out from this. ASAP!

**Comment by YanaXu** [comment]
Hi @KiranKumarGowda, could you please share your workflow file with us? 
I don't know if you use Azure Cli or Azure PowerShell to deploy the logic app or other GitHub Actions. If you're using other GitHub Actions, it's better to raise the issue in their repos. If you're using Azure Cli or Azure PowerShell, you can provide the information here and we'll see what we can do.

**Comment by KiranKumarGowda** [comment]
> Hi @KiranKumarGowda, could you please share your workflow file with us? I don't know if you use Azure Cli or Azure PowerShell to deploy the logic app or other GitHub Actions. If you're using other GitHub Actions, it's better to raise the issue in their repos. If you're using Azure Cli or Azure PowerShell, you can provide the information here and we'll see what we can do.

Hi @YanaXu , I'm not using other github actions . 
I have shared the workflows through mail , kindly check and let me know .

**Comment by YanaXu** [comment]
Hi @KiranKumarGowda ,

I see from your workflow file, you're using `azure/arm-deploy@v1` to deploy the logic app.

```yaml
      - uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{github.event.inputs.subscriptionId}}
          resourceGroupName: ${{github.event.inputs.resourceGroupName}}
          template:  ./ARMTemplates/LA_Standard_Basic.json
          parameters: ./ARMTemplates/LA_Standard_Basic_Param.json
```

It's out of our scope. I suggest you to raise an issue in its repo instead.
Based on your error message, it means you have created a `Website` named as `Demo121`. It's quite normal. You can try another name or delete it before the next try.

**Comment by YanaXu** [comment]
OK, please schedule a meeting with me.

**Comment by KiranKumarGowda** [comment]
> OK, please schedule a meeting with me.

join the meet

**Comment by KiranKumarGowda** [comment]
Run azure/powershell@v1
Validating inputs
Module Az latest installed from hostedAgentFolder
Initializing Az Module
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command Test-Path (Join-Path /opt/hostedtoolcache az_*)
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command $env:PSModulePath
/home/runner/.local/share/powershell/Modules:/usr/local/share/powershell/Modules:/opt/microsoft/powershell/7-lts/Modules
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command try ***
            $ErrorActionPreference = "Stop"
            $WarningPreference = "SilentlyContinue"
            $output = @***
            $data = Get-Module -Name Az -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1
            $output['AzVersion'] = $data.Version.ToString()
            $output['Success'] = "true"
        ***
        catch ***
            $output['Error'] = $_.exception.Message
        ***
        return ConvertTo-Json $output
False
***
  "AzVersion": "11.0.0",
  "Success": "true"
***
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command $env:PSModulePath
/opt/hostedtoolcache:/home/runner/.local/share/powershell/Modules:/usr/local/share/powershell/Modules:/opt/microsoft/powershell/7-lts/Modules
Initializing Az Module Complete
Running Az PowerShell Script
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command /runner/_work/_temp/f2217c91-92e7-44d8-b57d-8516b06274c4.ps1
Get-AzWebAppPublishingProfile: /runner/_work/_temp/f2217c91-92e7-44d8-b57d-8516b06274c4.ps1:2
Line |
   2 |  $profile = Get-AzWebAppPublishingProfile `
     |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Operation returned an invalid status code 'NotFound'

Error: Error: The process '/usr/bin/pwsh' failed with exit code 1

-----------------------------------------------------------------------------------------------------

This is the workflow 

name: build and deploy LA

on:
  workflow_dispatch:
    inputs:
      ResourceGroupName:
        description: 'Name of the Resource Group'
        required: true
      LogicAppName:
        description: 'Name of the Logic App'
        required: true


# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Paste the RBAC json into the following secret in your repository:
#   AZURE_RBAC_CREDENTIALS
#
# 2. Change these variables for your configuration:


jobs:
  build-and-deploy:
    runs-on: [ aks-gha-runners ]
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 

    - name: Get publish Profile
      id: fncapp
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $profile = Get-AzWebAppPublishingProfile `
              -ResourceGroupName ${{github.event.inputs.ResourceGroupName}} `
              -Name ${{github.event.inputs.LogicAppName}}
          $profile = $profile.Replace("`r", "").Replace("`n", "")
          Write-Output "::set-output name=profile::$profile"
        azPSVersion: latest
        
    - name: Create project folder
      run: |
        mkdir output
        cp 'host.json' 'output/'
        #cp 'proxies.json' 'output/'
        #cp 'connections.json' 'output/'
        cp -r 'Stateful1' 'output/'
    - name: Easy Zip Files
      uses: vimtor/action-zip@v1
      with:
        dest: '${{ github.run_id }}.zip'
        files: output/
        
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{github.event.inputs.LogicAppName}}
        package: '${{ github.run_id }}.zip'
        publish-profile: ${{steps.fncapp.outputs.profile}}  

Hi @YanaXu  Can u help me out this

**Comment by YanaXu** [comment]
Hi @KiranKumarGowda , the message `Operation returned an invalid status code 'NotFound'` said the resource is not found. It means it's not created.

**Comment by KiranKumarGowda** [comment]
Hi  , but yesterday we had run right  through  script , why did it was not
created ?

**Comment by YanaXu** [comment]
@KiranKumarGowda , what you have seen is a nomal and reasonable response from Azure.
Whatever client tools you use (ARM Deploy Action or Azure PowerShell cmdlets), if the Azure resource is there, it returns. 
If it's deleted, it returns "NotFound".

I think before you put every step in GitHub workflow file, it's better to test it locally. For example, on your laptop, connect to your Azure account, create the resource, get the resource, delete the resource, and try to get it again.
Maybe you can try some guides of "QuickStart" of Azure, Azure PowerShell, or other Azure Client tools.
