### ISSUE TITLE
@v1 Login doesn't read service principal "Not all values are present"

### ISSUE THREAD

**Issue by jeffwmartinez** [Azure/login#396]
I was using 1.4.6 and started getting a service principal error so I updated the service principal to a new one and still got an error.  I only mention that in case it's related, but I am now using the latest version and get the following error with more details regarding the service principal.  I've tried using **creds** first, then the individual parameters but it still says _Not all values are present_.

![image](https://github.com/Azure/login/assets/30853051/2a083081-1318-4821-8014-c54511f9293f)

![image](https://github.com/Azure/login/assets/30853051/ce263618-7c0d-4220-b51d-a0bb4349fb0f)

It says the result is null, but it's correctly saved as a secret in GitHub.  

I'm wondering if the action is recognizing the values correctly.  

workflow file link: https://github.com/Azure/AppService/blob/master/.github/workflows/deploy-to-staging-site.yml

workflow file zip:
[deploy-to-staging-site.zip](https://github.com/Azure/login/files/13836247/deploy-to-staging-site.zip)

**Comment by MoChilia** [comment]
Hi @jeffwmartinez, I found that your workflow is triggered by a pull request from a forked repo. In this case, credentials stored in main repo will not be passed to the runner. See https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow.

**Comment by jeffwmartinez** [comment]
That was the solution.  Thank you!
