### ISSUE TITLE
Az login failed using OIDC in self-host runner with exit code 1, how can I know the exact error?

### ISSUE THREAD

**Issue by qfai** [Azure/login#401]
Log of my workflow
##[debug]Evaluating condition for step: 'Log in to Azure using OIDC'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Log in to Azure using OIDC
##[debug]Loading inputs
##[debug]Evaluating: secrets.AZURE_CLIENT_ID
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'AZURE_CLIENT_ID'
##[debug]=> 
##[debug]Result: 
##[debug]Evaluating: secrets.AZURE_TENANT_ID
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'AZURE_TENANT_ID'
##[debug]=> '*'
##[debug]Result: '*'
##[debug]Evaluating: secrets.AZURE_SUBSCRIPTION_ID
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'AZURE_SUBSCRIPTION_ID'
##[debug]=> 
##[debug]Result: 
##[debug]Loading env
Run azure/login@v1
::add-mask::***
Running Azure CLI Login.
##[debug]Azure CLI path: C:\Program Files (x86)\Microsoft SDKs\Azure\CLI[2](https://github.com/microsoft/AdaptiveCloudLab-TF/actions/runs/7482988399/job/20367644193#step:3:2)\wbin\az.cmd
##[debug]Azure CLI version used:
##[debug]azure-cli                         2.56.0
##[debug]
##[debug]core                              2.56.0
##[debug]telemetry                          1.1.0
##[debug]
##[debug]Extensions:
##[debug]arcappliance                      0.2.27
##[debug]azure-iot-ops                    0.2.0b1
##[debug]azurestackhci                      0.2.[3](https://github.com/microsoft/AdaptiveCloudLab-TF/actions/runs/7482988399/job/20367644193#step:3:3)
##[debug]connectedvmware                   0.1.12
##[debug]customlocation                     0.1.3
##[debug]k8s-extension                      1.[4](https://github.com/microsoft/AdaptiveCloudLab-TF/actions/runs/7482988399/job/20367644193#step:3:4).2
##[debug]
##[debug]Dependencies:
##[debug]msal                            1.24.0b2
##[debug]azure-mgmt-resource             23.1.0b2
##[debug]
##[debug]Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
##[debug]Extensions directory 'C:\Users\mgodfre3\.azure\cliextensions'
##[debug]
##[debug]Python (Windows) 3.11.[5](https://github.com/microsoft/AdaptiveCloudLab-TF/actions/runs/7482988399/job/20367644193#step:3:5) (tags/v3.11.5:cce[6](https://github.com/microsoft/AdaptiveCloudLab-TF/actions/runs/7482988399/job/20367644193#step:3:6)ba9, Aug 24 2023, 14:21:31) [MSC v.1936 32 bit (Intel)]
##[debug]
##[debug]Legal docs and information: aka.ms/AzureCliLegal
##[debug]
##[debug]
**##[debug]Your CLI is up-to-date.**
##[debug]
**Error: Login failed with Error: The process 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd' failed with exit code 1. Make sure 'az' is installed on the runner. If 'enable-AzPSSession' is true, make sure 'pwsh' is installed on the runner together with Azure PowerShell module. Double check if the 'auth-type' is correct. Refer to https://github.com/Azure/login#readme for more information.
##[debug]Error: The process 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd' failed with exit code 1**
##[debug]    at ExecState._setResult (C:\Users\mgodfre3\actions-runner\_work\_actions\azure\login\v1\node_modules\@actions\exec\lib\toolrunner.js:592:25)
##[debug]    at ExecState.CheckComplete (C:\Users\mgodfre3\actions-runner\_work\_actions\azure\login\v1\node_modules\@actions\exec\lib\toolrunner.js:5[7](https://github.com/microsoft/AdaptiveCloudLab-TF/actions/runs/7482988399/job/20367644193#step:3:7)5:1[8](https://github.com/microsoft/AdaptiveCloudLab-TF/actions/runs/7482988399/job/20367644193#step:3:8))
##[debug]    at ChildProcess.<anonymous> (C:\Users\mgodfre3\actions-runner\_work\_actions\azure\login\v1\node_modules\@actions\exec\lib\toolrunner.js:46[9](https://github.com/microsoft/AdaptiveCloudLab-TF/actions/runs/7482988399/job/20367644193#step:3:9):27)
##[debug]    at ChildProcess.emit (node:events:513:28)
##[debug]    at maybeClose (node:internal/child_process:1[10](https://github.com/microsoft/AdaptiveCloudLab-TF/actions/runs/7482988399/job/20367644193#step:3:10)0:[16](https://github.com/microsoft/AdaptiveCloudLab-TF/actions/runs/7482988399/job/20367644193#step:3:16))
##[debug]    at Process.ChildProcess._handle.onexit (node:internal/child_process:[30](https://github.com/microsoft/AdaptiveCloudLab-TF/actions/runs/7482988399/job/20367644193#step:3:30)4:5)
##[debug]Node Action run completed with exit code 1
##[debug]AZURE_HTTP_USER_AGENT='GITHUBACTIONS/AzureLogin@v1_microsoft/AdaptiveCloudLab-TF'
##[debug]AZUREPS_HOST_ENVIRONMENT='GITHUBACTIONS/AzureLogin@v1_microsoft/AdaptiveCloudLab-TF'
##[debug]AZURE_HTTP_USER_AGENT=''
##[debug]AZUREPS_HOST_ENVIRONMENT=''
##[debug]Finishing: Log in to Azure using OIDC

----------------------------------------------------------------------------------------

workflow:

name: Site Deployment

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_USE_OIDC: true

jobs:
  terraform:
    name: 'Terraform'
    # runs-on: [ubuntu-latest]
    runs-on: [self-hosted]
    environment: terraform

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-directory }}

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Log in to Azure using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

**Comment by MoChilia** [comment]
Hi @qfai, could you try `azure/login@v1.6.0` and attach the debug information?

**Comment by qfai** [comment]
@MoChilia  ##[debug]Loading env
Run azure/login@v1.6.0
  with:
    client-id: ***
    tenant-id: ***
    subscription-id: ***
    enable-AzPSSession: false
    environment: azurecloud
    allow-no-subscriptions: false
    audience: api://AzureADTokenExchange
    auth-type: SERVICE_PRINCIPAL
  env:
    ARM_CLIENT_ID: ***
    ARM_SUBSCRIPTION_ID: ***
    ARM_TENANT_ID: ***
    ARM_USE_OIDC: true
##[debug]Azure CLI path: C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd
Clearing azure cli accounts from the local cache.
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account clear"
ERROR: Decryption failed: [WinError 87] None. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError
Error: Login cleanup failed with Error: The process 'C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd' failed with exit code 1. Make sure 'az' is installed on the runner. If 'enable-AzPSSession' is true, make sure 'pwsh' is installed on the runner together with Azure PowerShell module.
##[debug]Error: The process 'C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd' failed with exit code 1
##[debug]    at ExecState._setResult (C:\Users\mgodfre3\actions-runner\_work\_actions\azure\login\v1.6.0\node_modules\@actions\exec\lib\toolrunner.js:592:25)
##[debug]    at ExecState.CheckComplete (C:\Users\mgodfre3\actions-runner\_work\_actions\azure\login\v1.6.0\node_modules\@actions\exec\lib\toolrunner.js:575:18)
##[debug]    at ChildProcess.<anonymous> (C:\Users\mgodfre3\actions-runner\_work\_actions\azure\login\v1.6.0\node_modules\@actions\exec\lib\toolrunner.js:[46](https://github.com/microsoft/AdaptiveCloudLab-TF/actions/runs/7483890809/job/20369851550#step:2:46)9:27)
##[debug]    at ChildProcess.emit (node:events:[51](https://github.com/microsoft/AdaptiveCloudLab-TF/actions/runs/7483890809/job/20369851550#step:2:52)3:28)
##[debug]    at maybeClose (node:internal/child_process:1100:16)
##[debug]    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Pre Log in to Azure using OIDC

**Comment by MoChilia** [comment]
@qfai, this is caused by a decryption failure from MSAL. You can check more details in this issue https://github.com/Azure/azure-cli/issues/20278. 

Here are two potential solutions for you:

1.  Check if `azure/login@v1.5.0` works for you.
2. Run `az config set core.encrypt_token_cache=false` before `azure/login@v1`.

**Comment by qfai** [comment]
@MoChilia I haven' t tried these methods, I managed to pass by restarting the machine and using another account to run the self-host runner.
