### ISSUE TITLE
Roll back v1 tag to point to the same commit as 1.5.1

### ISSUE THREAD

**Issue by nuryupin-kr** [Azure/login#406]
Since 1.6.0 is broken for people who don't have az cli pre-installed, could you roll v1 tag back to a previous working commit?

**Comment by sblackstone** [comment]
This broke our build due to custom runners...

**Comment by ohbriansung** [comment]
Please consider rollback this change and then create a `v2.0.0` since this is a breaking change for anyone running self-hosted runner.

**Comment by YanaXu** [comment]
Let's track this in #403.
