### ISSUE TITLE
Error: Login failed with Error: Using auth-type: SERVICE_PRINCIPAL. Not all values are present.

### ISSUE THREAD

**Issue by Aholicknight** [Azure/login#408]
![firefox_20240113_EO4Qw7oVl2](https://github.com/Azure/login/assets/7843719/6a4b8849-ada5-4a78-a56d-3056707eb7c4)

Hello. I am having a problem where I am not able to push to my Azure Web App. I do not know why this is happening, and I did not make any changes to the Workflow auto-generated by Azure. How can I fix this problem? Is it a problem with Azure? I never had this problem before.

Thank you!

**Comment by MoChilia** [comment]
Hi @Aholicknight, based on the log you provided, it seems that `client-id` and `tenant-id` are missing when calling azure/login. Please provide these two parameters. And could you share your workflow here to help me better assist you with this issue?

**Comment by MoChilia** [comment]
@Aholicknight, please check if `__clientidsecretname__` and `.__tenantidsecretname__` are stored as secrets in your repository. See https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions for how to use secrets in GitHub Actions. I am wondering if these secrets are auto generated by azure web app?

**Comment by Aholicknight** [comment]
> @Aholicknight, please check if `__clientidsecretname__` and `.__tenantidsecretname__` are stored as secrets in your repository. See [docs.github.com/en/actions/security-guides/using-secrets-in-github-actions](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions) for how to use secrets in GitHub Actions. I am wondering if these secrets are auto generated by azure web app?

@MoChilia these secrets are automatically generated by Azure web app. I do not have any secrets in my repository.

**Comment by MoChilia** [comment]
I tried to reproduce your issue by setting CI/CD with GitHub Actions for an Azure web app in development center. It works well for me. I chose the Authentication type: User-assigned identity. Then the workflow was automatically generated in my GitHub repo with the corresponding secrets stored in my repo. 
![image](https://github.com/Azure/login/assets/72982571/1be9c0af-7e8f-4244-9f4b-0c57d1f00487)
![image](https://github.com/Azure/login/assets/72982571/d0a8abe0-b5c7-4b95-9c56-5e0905b15552)

It seems that an error occurred when Azure Web app is creating the user-assigned identity or when they are writing the secrets to your repository. You can report this issue to [Azure/webapps-deploy](https://github.com/Azure/webapps-deploy).

For a quick fix, I have some suggestions for you. I can find the managed identity created by Azure web app. If it was also created for you, you can copy its `Client ID` and `Tenant ID` to store them as secrets in your repository. If you cannot find such managed identity, you may refer to the guide on [how to login with OIDC](https://github.com/Azure/login?tab=readme-ov-file#login-with-openid-connect-oidc-recommended).

**Comment by Aholicknight** [comment]
@MoChilia I will try adding the repository secrets manually and see if that fixes the problem.

**Comment by Aholicknight** [comment]
I think I fixed it by setting the action setting in my organization "read and write" before it was set to "read only"

**Comment by ThadeusAjayi** [comment]
I guess the documentation is lacking some information. I struggled using environment secrets for in my own case:

>  client-id: ${{ secrets.AZURE_CLIENT_ID }}
    tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

However not until I added them as repository secret, before I got success.

**Comment by Godwin1010** [comment]
I'm getting the above error too this is my workflow file

 name: eShopOnWeb Build and Test

#Triggers (uncomment line below to use it)
on: [push, workflow_dispatch]

#Environment variables https://docs.github.com/en/actions/learn-github-actions/environment-variables
env:
  RESOURCE-GROUP: GODWIN-RG
  LOCATION: westeurope
  TEMPLATE-FILE: infra/webapp.bicep
  SUBSCRIPTION-ID: 23f9acd5-afdf-451a-bea4-2fef9a758f90
  WEBAPP-NAME: eshoponweb1-webapp1

jobs:
  #Build, test and publish .net web project in repository
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      #checkout the repository
      - uses: actions/checkout@v5
      #prepare runner for desired .net version SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.x"
          dotnet-quality: "preview"
      #Build/Test/Publish the .net project
      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release
      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release
      - name: dotnet publish
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
          cd ${{env.DOTNET_ROOT}}/myapp
          zip -r ../app.zip .
      # upload the published website code artifacts
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v5
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/app.zip

      # upload the bicep template as artifacts for next job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v5
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE-FILE }}

  # Use Bicep to deploy infrastructure + Publish webapp
  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: "Development"
    steps:
      #Download the publish files created in previous job
      - name: Download artifact from build job
        uses: actions/download-artifact@v6
        with:
          name: .net-app
          path: .net-app

      #Download the bicep templates from previous job
      - name: Download artifact from build job
        uses: actions/download-artifact@v6
        with:
          name: bicep-template
          path: bicep-template

      #Login in your azure subscription using a service principal (credentials stored as GitHub Secret in repo)
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Azure WebApp using Bicep file
      - name: deploy
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION-ID }}
          resourceGroupName: ${{ env.RESOURCE-GROUP }}
          template: bicep-template/webapp.bicep
          parameters: "webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}"
          failOnStdErr: false

      # Publish website to Azure App Service (WebApp)
      # Step disabled due to issue where the site sometimes can't be found: https://github.com/microsoft/pipelines-appservice-lib/issues/56. Instead deploy using CLI
      - name: Publish Website to WebApp
        if: false #Disable step due to comment above
        uses: Azure/webapps-deploy@v3
        with:
          type: ZIP
          app-name: ${{ env.WEBAPP-NAME  }}
          package: .net-app/app.zip

      # Publish website to Azure App Service using CLI (WebApp)
      - name: Publish Website to WebApp
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az webapp deploy --name ${{ env.WEBAPP-NAME }} --resource-group ${{ env.RESOURCE-GROUP }} --src-path .net-app/app.zip --type zip
