### ISSUE TITLE
`Node.js 16 actions are deprecated. `

### ISSUE THREAD

**Issue by afifurrohman-id** [Azure/login#412]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: `azure/login@v1`, `azure/container-apps-deploy-action@v2`. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by MoChilia** [comment]
Hi @afifurrohman-id, thanks for your suggestion, it's already in our plan. Let's track this in https://github.com/Azure/login/issues/357.
