### ISSUE TITLE
Symbols in az-cli generated clientSecret breaks login

### ISSUE THREAD

**Issue by walzph** [Azure/login#42]
Following [this](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-github-action) guide, most people probably just copy&paste the JSON output generated by the service principal creation via _az-cli_ to their Github secrets.

However the generated _clientSecret_ often contains symbols which must be escaped in order to work in the `az login` command performed in the Github Action.

For example:
_az-cli_ generated a _clientSecret_ which includes `avc!bH9;5<d9L,M!`.  
This breaks the login process without a meaningful error mesasge. It works if it's escaped to `avc\!bH9\;5\<d9L\,M\!` before being inserted here:
```
executeAzCliCommand(`login --service-principal -u "${servicePrincipalId}" -p "${servicePrincipalKey}" --tenant "${tenantId}"`, true);
```

**Comment by arjgupta** [comment]
@walzph thanks for reporting the issue. We will add logic to escape special characters in client secret.

**Comment by aksm-ms** [comment]
@walzph Can you please paste the error logs and also the logs after escaping the secret here?

**Comment by aksm-ms** [comment]
Issue is fixed in PR.
