### ISSUE TITLE
Update node version

### ISSUE THREAD

**Issue by saliceti** [Azure/login#420]
We're receiving warnings as node16 is deprecated:
>Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: Azure/login@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by MoChilia** [comment]
The update of node 16 has been merged into the master branch in #411. We are currently planning to release a new version. It is scheduled no later than March. I'll keep this issue open and notify you as soon as the release is ready.

**Comment by h-no** [comment]
> The update of node 16 has been merged into the master branch in #411. We are currently planning to release a new version. It is scheduled no later than March. I'll keep this issue open and notify you as soon as the release is ready.

Node 16 has been EOL since September 11th, 2023 so we might as well wait to March.

**Comment by QuintinWillison** [comment]
> The update of node 16 has been merged into the master branch in #411. We are currently planning to release a new version. It is scheduled no later than March. I'll keep this issue open and notify you as soon as the release is ready.

Thanks, @MoChilia - can you define "no later than March"? I was hoping it might be "no later than 1 March 2024", but am wondering if you meant "at some point in March"?

This is the only action across our repositories that can't be upgraded and GitHub have been equally mysterious about when they'll phase out Node.js 16 support.

**Comment by MoChilia** [comment]
Hello everyone, we've just released `azure/login@v2`. Please update your workflow to use `azure/login@v2` to apply this change. Thank you all for your patience. Give this new version a try!
