### ISSUE TITLE
v2.0.0 tag missing

### ISSUE THREAD

**Issue by martincostello** [Azure/login#425]
While the v2 tag exists, for repositories using the action pinned by SHA, the lack of a v2.0.0 tag means that Dependabot does not see a new version as available for use (compared to when using the v1 tag, which it does).

A v2.0.0 tag that points to the same SHA as v2 currently points to should be created.

**Comment by MoChilia** [comment]
Hi @martincostello, thanks for your suggestion! I've created a v2.0.0 tag. Feel free to reopen the issue if you have any further questions.
