### ISSUE TITLE
Adding creds for an existing service principal

### ISSUE THREAD

**Issue by sebastiangonsal** [Azure/login#43]
How do i get creds for an existing service principal? The example to get the creds json creates a new principal. 

If i do something like :
```az ad sp show --id {app-id}```
I get a json that does not have client secret .

**Comment by arjgupta** [comment]
@sebastiangonsal there is no way to view the client secret. But you can go and create a new secret for the service principal. go to the Azure Portal. Search for 'App Registrations' resource. then search for the client id that you want to set secret for. The page should show you the Service Principal. Click on the service principal. From the blade on the left side, go to the 'Certificates & Secrets' setting. here you can create a new secret for the service principal. Either you can note it down somewhere or store it in the key vault.
