### ISSUE TITLE
Structure data such as the Azure Credential for service principal should not be stored as a Github Secret 

### ISSUE THREAD

**Issue by tleerai** [Azure/login#434]
References:

This Action's documentation recommends using Github Secret:
https://github.com/Azure/login?tab=readme-ov-file#login-with-a-service-principal-secret

Github's documentation (which this Action links to) advises not to use Github Secrets.
https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#naming-your-secrets

> To help ensure that GitHub redacts your secret in logs, avoid using structured data as the values of secrets. For example, avoid creating secrets that contain JSON or encoded Git blobs.

Doing this also has unintended side affects of clobbering any output that has structured data, such as braces and replaces it with `***`.

This action should instead be changed to accept base64 encoded AZURE_CREDENTIAL

**Comment by YanaXu** [comment]
Hi @tleerai , the action recommend using OIDC not secret.
![image](https://github.com/Azure/login/assets/12843157/1642e1a0-f7f8-44f9-8392-0dade2bb5e7c)

Base64 encoding or not make no difference in the action. We suggest you to use GitHub secret.
