### ISSUE TITLE
v1 tag points to the buggy v1.6.0 instead of the v1.6.1 release which has the fix

### ISSUE THREAD

**Issue by archittsc** [Azure/login#437]
A few hours ago our pipelines using the az login@v1 started to break with issue #403, upon checking the v1 tag I see it points to v1.6.0, I think this issue was fixed in v1.6.1 and the v1 tag was updated to 1.6.1 but maybe somehow a few hours back v1 got tagged with v1.6.0 it seems. Please have a look and update the v1 tag to v1.6.1. 

Workaround: Momentarily we have switched to using v1.6.1 explicitly in our pipelines and they work fine as they used to.

**Comment by DigiaLahtinen-Corin** [comment]
We have exactly the same problem in all our pipelines and the same workaround fortunately worked v1.6.1

**Comment by MitchellPaff** [comment]
same issue in our pipelines

**Comment by MoChilia** [comment]
Hi @archittsc, @DigiaLahtinen-Corin, sorry for inconvenience, it's already fixed.
