### ISSUE TITLE
Inconsistent login speed / slow login

### ISSUE THREAD

**Issue by lanni-energinet** [Azure/login#449]
We are facing issues with azure/login being slow
Duration is from ~13 seconds to ~1½ minutes, we are using large runners (ubuntu-latest)

One of the most consistent findings is the command which takes about 11s
```/usr/bin/az --version```

```
let output: string = "";
const execOptions: any = {
    listeners: {
        stdout: (data: Buffer) => {
            output += data.toString();
        }
    }
};

await this.executeAzCliCommand(["--version"], true, execOptions);
core.debug(`Azure CLI version used:\n${output}`);
```

We have been unable to reproduce the error outside of our existing workflows. but even considering that - it seems a bit redundant to execute a command and then disregard the output based on loglevel

Would it make sense to wrap the quoted code in a conditional block based on `core.isDebug()`

Details below

**Usage in workflow:**
```
- name: Az CLI login
uses: azure/login@v2
with:
  client-id: ${{ inputs.azure_spn_id }}
  tenant-id: ${{ inputs.azure_tenant_id }}
  subscription-id: ${{ inputs.azure_subscription_id }}
```

**Output from our log (With debug enabled)**

```
2024-05-22T08:31:07.0288811Z ##[group]Run azure/login@v2
2024-05-22T08:31:07.0289280Z with:
... snip ...
2024-05-22T08:31:07.0293203Z env:
... snip ...
2024-05-22T08:31:07.0299672Z ##[endgroup]
2024-05-22T08:31:07.0688122Z ::add-mask::***
2024-05-22T08:31:07.0698936Z Running Azure CLI Login.
2024-05-22T08:31:07.0721267Z ##[debug]Azure CLI path: /usr/bin/az
2024-05-22T08:31:18.4592979Z ##[debug]Azure CLI version used:
2024-05-22T08:31:18.4593850Z ##[debug]azure-cli                         2.60.0 *
... snip ...
2024-05-22T08:31:18.4608366Z ##[debug]
2024-05-22T08:31:18.4611258Z [command]/usr/bin/az cloud set -n azurecloud
2024-05-22T08:31:49.5759670Z Done setting cloud: "azurecloud"
```

**Comment by MoChilia** [comment]
Hi @lanni-energinet, thanks for bringing this to our attention! We can definitely enhance this.

I've found related issues, as noted in https://github.com/Azure/azure-cli/issues/27796#issuecomment-1801447309. The `az --version` performs an update check, which can be slow with a poor network connection. On the other hand, `az version` doesn't make any network requests and is faster. I will change `az --version` to `az version` to improve the speed of azure/login.

**Comment by lanni-energinet** [comment]
@MoChilia Can you speculate on when this issue is released?

**Comment by onionhammer** [comment]
It is very very slow. It shouldnt take 1 minute to run this, but its consistently inconsistent.

**Comment by lanni-energinet** [comment]
@onionhammer 

Please upvote this issue https://github.com/actions/runner-images/issues/10110 as this heavily impacts the speed of az-login (If it is the first step that interacts with az-cli)

**Comment by lanni-energinet** [comment]
@YanaXu / @MoChilia 

Could you please release a new version. 

Our organization is wasting time and money on
