### ISSUE TITLE
Change in subject claim

### ISSUE THREAD

**Issue by AlexAxthelm** [Azure/login#453]
Hi, we've been happily using `azure/login` for a while now, but we've encountered an unexpected issue today.

We have a GH workflow which calls another workflow from another repo, which in turn calls `login` (which has been working well for months)

However, as we were pushing to the branch today, the workflow failed with the message
```
Error: AADSTS700213: No matching federated identity record found for presented assertion subject 'repo:RMI-PACTA/workflow.transition.monitor:ref:refs/heads/update-scenario-es'. Please check your federated identity credential Subject, Audience and Issuer against the presented assertion. https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation Trace ID: 8335980a-8604-4005-a5e1-f678003d5b01 Correlation ID: c3a1f4bb-2b8a-4486-ac4a-fdd45ed43116 Timestamp: 2024-05-31 14:26:23Z
```
https://github.com/RMI-PACTA/workflow.transition.monitor/actions/runs/9314690620/job/25654928761#step:5:19

What stands out here, is that I would expect the assertion subject to be `pull_request` (and we have set up federated credentials aginst the `pull_request` Entity)

From the failing run:
```
subject claim - repo:RMI-PACTA/workflow.transition.monitor:ref:refs/heads/update-scenario-es
```
https://github.com/RMI-PACTA/workflow.transition.monitor/actions/runs/9314690620/job/25654928761#step:5:17

From a run **on the same branch** yesterday:
```
subject claim - repo:RMI-PACTA/workflow.transition.monitor:pull_request
```
https://github.com/RMI-PACTA/workflow.transition.monitor/actions/runs/9304676958/job/25610128853#step:5:17

We haven't changed any of our workflow files in between, and it seems like all the latest updates to your action were pushed last week, so I'm not sure why this behavior is changing now.

Do you have any suggestions?

Link to the called workflow: https://github.com/RMI-PACTA/workflow.prepare.pacta.indices/blob/df23fb1a6f5d85b8635c1bbc28de6db76294c062/.github/workflows/run-index-preparation.yml#L48-L54

Link to calling workflow: https://github.com/RMI-PACTA/workflow.transition.monitor/blob/7591a74a826a02fa12b86bb41ef8b8ea71931355/.github/workflows/build-push-private.yml#L110-L125

We're using `azure/login@v2`.

**Comment by YanaXu** [comment]
Hi @AlexAxthelm , could you please check the "Federated credential" configured on the SP? For example:
![image](https://github.com/Azure/login/assets/12843157/e979d6b7-3345-4d20-aa63-a6b94849f81a)

It looks like someone update or delete the federated credentials.

**Comment by AlexAxthelm** [comment]
Interesting. When I looked at the credentials on Friday, everything was as I expected it to be, but in any case, the action seems to be working again.

Thanks for your help.

--Alex
