### ISSUE TITLE
Docs on creating credentials misleading when not doing a Logic app

### ISSUE THREAD

**Issue by brettcannon** [Azure/login#46]
When I tried to run the example `az ad` command I followed the example and `--name "GitHub Actions"` failed as the name isn't for the token but for a Logic app. So maybe drop `--name` from the example?

**Comment by AmrutaKawade** [comment]
yes. with --name option, service principle will be created with access to only that application within resource. if you want to access all applications within resource you can skip --name option.

**Comment by N-Usha** [comment]
@brettcannon - Hope your query got answered. Closing the issue. Thanks again for reaching out out to us.

**Comment by brettcannon** [comment]
It did answer my question, but the README is still a bit misleading in how the example for generating credentials lists `--name` as part of it but doesn't mention it's an optional aspect to it.

**Comment by N-Usha** [comment]
Thanks for pointing that out @brettcannon. I enhanced the Readme file to explain the part further. Hope it helps.
