### ISSUE TITLE
Validation failed in datafactory artifacts

### ISSUE THREAD

**Issue by Logeswari25** [Azure/login#460]
Hi,

I encountered an error during the validation of Data Factory artifacts while deploying the pipeline. It is successful in ADF validate all option but failure in git validate option. 

![ADF_ValidationErrror](https://github.com/Azure/login/assets/149675131/0a243adb-a29e-4e72-8176-f13294523719)
 

![ADF_validationFailed](https://github.com/Azure/login/assets/149675131/8381d9e8-e235-4242-a80b-211df4e57593)

Can you please assist me with this?

**Comment by MoChilia** [comment]
Hi @Logeswari25, this issue doesn't appear to come from `azure/login`. Are you reporting it in the correct repository? If your issue is related to `azure/login`, please share your workflow here.

**Comment by Logeswari25** [comment]
I am reporting this issue in the correct repository. This is not related to azure/login. While deploying a pipeline, I encountered a validation error despite having merged changes to the main branch. Consequently, the next deployment also resulted in an error.

Could you please assist in resolving this validation issue?

**Comment by MoChilia** [comment]
@Logeswari25, which GitHub action are you using?

**Comment by Logeswari25** [comment]
[Azure/data-factory-validate-action@v1.1.5]

**Comment by Logeswari25** [comment]
below is the workflow:

validate_adf:
    runs-on: self-hosted
    steps:      
      - uses: actions/checkout@v3
      - name: Validate Data Factory resources
        uses: Azure/data-factory-validate-action@v1.1.5
        with:
          path: datafactory/

**Comment by MoChilia** [comment]
@Logeswari25, could you open this issue in https://github.com/Azure/data-factory-validate-action/issues?
