### ISSUE TITLE
Update the "secrets" url in README

### ISSUE THREAD

**Issue by harjas27** [Azure/login#47]
In the README.md file, the url for creating and using encrypted secret variables is not correct. 
The link points to https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#creating-and-using-secrets-encrypted-variables
But should be updated to https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

**Comment by N-Usha** [comment]
Thanks @harjas27 and @johnlokerse for raising the issue and helping us fix this too. Really appreciate 👍
