### ISSUE TITLE
When is the new release?

### ISSUE THREAD

**Issue by ltutar** [Azure/login#476]
Hi,

I was wondering when we can expect a higher release than v2.1.1 which is from 24th of May 2024. 
I can not find it in https://github.com/Azure/login/issues/424 
I am waiting for a fix that resolves the "Login cleanup failed with Error: Unable to locate executable file: az." issue.

Thank you in advance.

Levent

**Comment by MoChilia** [comment]
Do you mean the issue #403? It was resolved in `v1.6.1`. Since that release, the cleanup step no longer fails with the 'az not found' error.

**Comment by ltutar** [comment]
@MoChilia Thank you for your answer. I want to use version 2.

login@v1 is giving the warning:
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: azure/login@v1

login@2.1.1 is giving the error:
Login cleanup failed with Error: Unable to locate executable file: az. Please verify either the file path exists or the file can

**Comment by MoChilia** [comment]
Could you share your workflow and the entire logs? I've checked that cleanup failed only cause warning in v2.1.1, see https://github.com/Azure/login/blob/v2.1.1/src/cleanup.ts#L12-L15.

**Comment by ltutar** [comment]
Hi @MoChilia 
v2.1.1 is indeed a giving a warning but the warning message is using the word "error". This is confusing the team.
`Login cleanup failed with Error: Unable to locate executable file: az. `
I was hoping that with a new v2 version, this should be solved.

![Screenshot 2024-07-25 at 12 50 13](https://github.com/user-attachments/assets/046675f5-16ed-4c58-9bc4-9a8883b8c445)
![Screenshot 2024-07-25 at 12 48 22](https://github.com/user-attachments/assets/42a9e6c3-1676-46ec-a5ca-e6d1a51a2a16)


![Screenshot 2024-07-25 at 12 48 22](https://github.com/user-attachments/assets/46e2ed66-d15f-4d89-880b-8591f3cbaf94)

**Comment by YanaXu** [comment]
Hi @ltutar, we've released a new version [v2.2.0](https://github.com/Azure/login/releases/tag/v2.2.0). In this version, we removed the `pre` step and add 2 env variables to enable/disable pre or post cleanup.
`v2` is aligned with `v2.2.0` now.
Please try the new version. You can also refer to [Enable/Disable the cleanup steps](https://github.com/Azure/login/tree/v2.2.0?tab=readme-ov-file#enabledisable-the-cleanup-steps).

**Comment by ltutar** [comment]
Thank you @YanaXu With this new release, I have a cleaner GitHub action runs.
