### ISSUE TITLE
📢We're now open to meet and talk for GitHub Actions with you.

### ISSUE THREAD

**Issue by Jacekey23** [Azure/login#480]
Hi,
Our team recently is opening to collect your feedback and suggestions on our GitHub Action. This helps us to value our user's input to build out more functionality based on the real detractors and delighters. 

If you'd like to talk to us, please reach out to mingxuli@microsoft.com, yanxu1@microsoft.com or shiyingchen@microsoft.com and we'll make it happen!

Thanks,
Azure Login Action team

**Comment by damianh** [comment]
I suggest enabling discussions on the repo instead of doing email.

**Comment by lanni-energinet** [comment]
I suggest responding to issues and mentions

**Comment by matsest** [comment]
If you are open to collect feedback see: https://github.com/Azure/login/issues/489 @Jacekey23 @MoChilia @YanaXu
