### ISSUE TITLE
Login Action backend is not up to date

### ISSUE THREAD

**Issue by marvinbuss** [Azure/login#49]
Please keep the backend up to date, so that users are not receiving these messages:

`Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
You have 3 updates available. Consider updating your CLI installation with 'sudo apt-get update && sudo apt-get install --only-upgrade -y azure-cli'. Detailed instructions can be found at https://aka.ms/doc/UpdateAzureCliApt`

This Action should receive continuous updates, if you want it to be the central Action for all Azure Actions.

Also, when setting `enable-AzPSSession: true ` the login takes ~5 mins. This must be improved.

**Comment by aksm-ms** [comment]
@marvinbuss can you please share the workflow used?

**Comment by aksm-ms** [comment]
@marvinbuss Can you please confirm if you are using Github hosted runner and if so, which one?

**Comment by marvinbuss** [comment]
I am not. I am just running it on GH. Just give it a try.

**Comment by aksm-ms** [comment]
@marvinbuss Can you please share your workflow?

**Comment by aksm-ms** [comment]
I understand your issue, need to your workflow to understand on which runners we need to update az cli.

**Comment by marvinbuss** [comment]
I was using `ubuntu-latest`. Thanks for your quick reply.

**Comment by hugogirard** [comment]
I confirm, I am using the runner ubuntu-latest and using the action azure login and it takes 5 minutes.  This is too long, and I have this message showing up.

You have 3 updates available. Consider updating your CLI installation with 'az upgrade'

**Comment by hugogirard** [comment]
It takes time only when the property enable-AzPSSession is set to true.

**Comment by aksm-ms** [comment]
@hugogirard Regarding time taken for enable-AzPSSession: true, we are working on it. 
@marvinbuss Thanks for reaching out. We are closing this issue as we have made required changes to address this.
