### ISSUE TITLE
Clarity on the use of 'auth-type' and its values

### ISSUE THREAD

**Issue by MadeehaKhan** [Azure/login#493]
Hi, I've been trying to deploy a static web app from Azure, and I believe I have all the pieces set up for a service principle with OIDC, but am still seeing the following error: 

![Image](https://github.com/user-attachments/assets/c264760e-f620-41c1-a1f9-1a68604dab98)

Here is what my workflow file looks like:
`jobs:
  build_job:
    runs-on: self-hosted
    steps:
      - name: Log in to Azure
        uses: Azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Install Azure CLI Latest
        uses: Azure/cli@v2.1.0
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            az storage -h
            
      - name: Install Azure Static Web Apps CLI
        run: npm install -g @azure/static-web-apps-cli`

I don't know what I could be doing wrong, since I am not seeing any errors when I deploy my app to preview, and my runner is just telling me that my job failed.

**Comment by MoChilia** [comment]
Hi @MadeehaKhan, have you installed `azure-cli` on your runner?

**Comment by MadeehaKhan** [comment]
> Hi [@MadeehaKhan](https://github.com/MadeehaKhan), have you installed `azure-cli` on your runner?

I have, it's a ubuntu machine and I installed it there but my job isn't even running past the login step

**Comment by MadeehaKhan** [comment]
![Image](https://github.com/user-attachments/assets/782ecec7-28a8-487d-adbb-ab348da38f93)

I'm now seeing these error messages. Previously to solve the subscription issue I would specify the tenant id while logging in but am not sure if that fits with this workflow especially because i am using the Azure action

**Comment by MoChilia** [comment]
@MadeehaKhan, if you would like to log in at tenant level, you can set `allow-no-subscriptions` to `true` in the action.
