### ISSUE TITLE
Certificate Login is not supported in Azure/login

### ISSUE THREAD

**Issue by vishalholla27** [Azure/login#496]
Hi,

We are using 
- name: Check Az Login
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

and AZURE_CREDENTIALS contains
{
    "clientId": "c***************a",
    "clientSecret": "PATH TO /spn.pem",
    "subscriptionId": "a*********1",
    "tenantId": "************************",
    "resourceManagerEndpointUrl": "https://management.azure.com/"
}

VM : Linux

Its throwing error :

Done setting cloud: "azurecloud"
Note: Azure/login action also supports OIDC login mechanism. Refer https://github.com/azure/login#configure-a-service-principal-with-a-federated-credential-to-use-oidc-based-authentication for more details.

Attempting Azure CLI login by using service principal with secret...
Error: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '***'. Trace ID: adc7aeb6-d440-4bae-8851-83f2f9780f00 Correlation ID: 8a8d0535-b475-4ca6-b86d-73458391e73c Timestamp: [20](https://github.com********************************/33692320017#step:4:21)24-11-29 09:14:56Z

Error: The error may be caused by passing a service principal certificate with --password. Please note that --password no longer accepts a service principal certificate. To pass a service principal certificate, use --certificate instead.

Error: Login failed with Error: The process '*********/.local/bin/az' failed with exit code 1. Double check if the 'auth-type' is correct. Refer to https://github.com/Azure/login#readme for more information.

**Comment by MoChilia** [comment]
Azure/login doesn't support certificate login. Passing a certificate path to creds will cause a failure when enabling the AzPS Session.

The reason why you failed to login with certificate now is because starting from Azure CLI version 2.67.0 (https://github.com/Azure/azure-cli/issues/30283), the `--password` parameter for `az login` no longer accepts service principal certificates. Instead, use the new `--certificate` parameter to pass a service principal certificate.

Please consider using OIDC login instead, as described in the https://github.com/Azure/login?tab=readme-ov-file#login-with-openid-connect-oidc-recommended. If you still prefer to use a certificate, here is the workaround:
```yaml
    steps:
      - name: Azure login with certificate
        run:
            az login --service-principal --username <client ID> --tenant <tenant id> --certificate <PATH TO /spn.pem>
            az account set --subscription <subscription ID>
```

**Comment by vishalholla27** [comment]
Thanks ! Its working

**Comment by Ravindra-R-reddy** [comment]
@MoChilia This issue has been closed and suggestion given here was using az login command for certificates.
But this doesn't solve the issue mentioned in #500 especially using certificate with service principle as creds for azure/login@v2

**Comment by MoChilia** [comment]
@Ravindra-R-reddy, thank you for the suggestion, but currently Azure/login does not plan to support certificate login, as OIDC login is the recommended one.

**Comment by Ravindra-R-reddy** [comment]
@MoChilia Would you please update the documentation to add a disclaimer for not using certificate path in **creds** object for azure/login@v2 action?

**Comment by MoChilia** [comment]
@Ravindra-R-reddy, Azure/login does not document support for certificate login. According to the [Azure/login README](https://github.com/Azure/login?tab=readme-ov-file#login-with-a-service-principal-secret), 
> clientSecret: the service principal client secret

`clientSecret` in `creds` should contain only the service principal client secret, not a certificate path. Providing a certificate path in creds will result in a failure when enabling the AzPS Session.

**Comment by ThomasAunvik** [comment]
Hey, so I am not sure if this fits this specific issue, but i am using the command
`az ad sp create-for-rbac --name "GithubActions" --role contributor --scopes /subscriptions/id/resourceGroups/rg --sdk-auth`
to generate the login, and i am suddenly getting an error when logging in? Is this not the way to do?

As this worked before, but suddenly now it just fails.

![Image](https://github.com/user-attachments/assets/f2b8d9cf-f6b5-43c8-a956-f4b1548c8207)

CLIENT CREDENTIALS:
```
{
  "clientId": "fc467e3c-...",
  "clientSecret": "fUJ8Q~...",
  "subscriptionId": "3c2a5c2c-...",
  "tenantId": "e6ffdf95-...",
  "activeDirectoryEndpointUrl": "https://login.microsoftonline.com",
  "resourceManagerEndpointUrl": "https://management.azure.com/",
  "activeDirectoryGraphResourceId": "https://graph.windows.net/",
  "sqlManagementEndpointUrl": "https://management.core.windows.net:8443/",
  "galleryEndpointUrl": "https://gallery.azure.com/",
  "managementEndpointUrl": "https://management.core.windows.net/"
}
```

```yml
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
```

**Comment by MoChilia** [comment]
Hi @ThomasAunvik, your case isn't related to this issue. It appears that you might be using an invalid secret to log in. To troubleshoot, please verify that the client credential is correctly stored in your GitHub secrets. Pay particular attention to ensure no characters are accidentally missing from the clientSecret. If the error persists, please open a new issue, and I'll assist you there.
