### ISSUE TITLE
Federated Identity Credentials now use case-sensitive matching

### ISSUE THREAD

**Issue by BillmanH** [Azure/login#497]
Deploying a previously working pipeline stopped when AZ Login made changes (links below). I've been reviewing docs but I can't find a way to remedy. 

My application is a Django Website hosted on Azure Web App Services. The deployment file.yaml is automatically generated by Azure App Services, so I don't really know what I'm supposed to change. It automatically creates the environment secrets as well. 

The the pipeline: https://github.com/BillmanH/exoplanets/actions/runs/12121138319/job/33791478871
The build.yaml: https://github.com/BillmanH/exoplanets/blob/main/.github/workflows/main_exodestiny.yml

The process is connected to GH through the default connector: 
![Image](https://github.com/user-attachments/assets/04ba31e7-24aa-40ed-b2c8-1b8faa51c98f)

The error:
```
Error: AADSTS7002138: No matching federated identity record found for presented assertion subject 'repo:BillmanH/exoplanets:environment:Production'. The subject matches with case-insensitive comparison, but not with case-sensitive comparison. Check your federated identity credential Subject, Audience and Issuer against the presented assertion. See documentation at: https://learn.microsoft.com/entra/workload-id/workload-identity-federation. See breaking change notification and remediation at: https://learn.microsoft.com/en-us/entra/identity-platform/reference-breaking-changes#august-2024. Trace ID: 996708da-0191-4988-a3c3-00fc96a03501 Correlation ID: 1a333cae-e34a-4960-a43a-8815307975fb Timestamp: 2024-12-02 17:28:39Z

Error: Interactive authentication is needed. Please run:
az login

Error: Login failed with Error: The process '/usr/bin/az' failed with exit code 1. Double check if the 'auth-type' is correct. Refer to https://github.com/Azure/login#readme for more information.
```
https://github.com/Azure/login#readme
https://learn.microsoft.com/entra/workload-id/workload-identity-federation
https://learn.microsoft.com/en-us/entra/identity-platform/reference-breaking-changes#august-2024

As this is a pretty generic workflow for Azure Web App deployment, I imagine others will find the answer helpful. My repo is public which will make it easier for other users to see what they can change. 

My question:
What do I need to do to make the pipeline run again. The links above and the readme offer a lot of information, but none of it directs me to "What I need to change in the pipeline?".  Can you offer me some clues?

**Comment by MoChilia** [comment]
Hi @BillmanH, according to the Note session given in https://learn.microsoft.com/en-us/entra/identity-platform/reference-breaking-changes#august-2024, please update the environment name property in your workflow from "Production" to "production" to comply with Azure App Service's requirements.

**Comment by BillmanH** [comment]
Hey, it was exactly what was in the instructions. Thanks for the pointer I really appreciate it. I was thinking it was a secret somewhere not the actual name of the environment. 

For others who have the same issue (in case there are any), the actual deploy steps are case sensitive.  So in [line 55 of my workflow](https://github.com/BillmanH/exoplanets/blob/main/.github/workflows/main_exodestiny.yml). 

```yaml
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'  <--- this right here. 
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
```

The file is generated automatically by Azure Webapp, so it could be possible that this comes up again. 

Thanks team!
