### ISSUE TITLE
OIDC login intermittently failing with error 'AADSTS500031: Cannot find signing certificate configured.'

### ISSUE THREAD

**Issue by lancelind** [Azure/login#499]
Starting today our workflow runs in Azure have intermittently started failing in the azure/login component with error 'AADSTS500031: Cannot find signing certificate configured.'

We use OIDC login with the following configuration:

      - name: Login to Azure
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

Task output:

Run azure/login@v2
Running Azure CLI Login.
/usr/bin/az cloud set -n azurecloud
Done setting cloud: "azurecloud"
Federated token details:
 issuer - https://token.actions.githubusercontent.com
 subject claim - repo:{org}/{repo}:environment:{env}   <- redacted actual values
Attempting Azure CLI login by using OIDC...
Error: AADSTS500031: Cannot find signing certificate configured. Trace ID: xxxx Correlation ID: yyyy Timestamp: 2024-12-06 00:21:19Z

Error: Interactive authentication is needed. Please run:
az login

Error: Login failed with Error: The process '/usr/bin/az' failed with exit code 1. Double check if the 'auth-type' is correct. Refer to https://github.com/Azure/login#readme for more information.

What we have tried:
- Given the mention of breaking changes with the latest version of az cli we've tried downgrading to earlier version.  No luck.
- Changing to a different Managed Identity. No luck.
- Upgrading to latest action (2.2.0). No luck.

**Comment by MoChilia** [comment]
Hi @lancelind, this issue isn't related to the recent breaking change in Azure CLI. The error occurs due to using OIDC login. Could you check if [this](https://learn.microsoft.com/en-us/answers/questions/141320/aadsts500031-cannot-find-signing-certificate-confi) solve your issue?
