### ISSUE TITLE
JSON returned from create-for-rbac isn't in the corrected format

### ISSUE THREAD

**Issue by bruno-brant** [Azure/login#5]
I'm trying to use GitHub actions to publish an Azure web app for the first time and I encountered a problem. The README tells me that I should store the JSON returned from `az ad sp create-for-rbac (...)` in a secret, however, it seems that _that_ JSON isn't what the action is actually expecting. 

For instance, I got the following JSON:

```js
{
  "appId": "<GUID>",
  "displayName": "<APPNAME>",
  "name": "http://<APPNAME>",
  "password": "<GUID>",
  "tenant": "<GUID>"
}
```

And that resulted in an error: 

> ##[error]Error: Not all values are present in the creds object. Ensure clientId, clientSecret, tenantId and subscriptionId are supplied
> ##[error]Node run failed with exit code 1

So, a friend realized that the original JSON fields have to be renamed, `password` is `clientSecret`, `tenant` is `tenantId`, `appId` is `clientId`... and there's no subscription.

**Comment by ardacetinkaya** [comment]
If I do not add subscription key, I got the " Not all values are present in the creds object. Ensure clientId, clientSecret, tenantId and subscriptionId are supplied" error. So I added it and login action is succeeded.

Valid JSON as secret is like below;

```
{
  "clientId": "",          <----- mandatory
  "displayName": "",
  "name": "",
  "subscriptionId":"",     <----- mandatory
  "clientSecret": "",      <----- mandatory
  "tenantId": ""           <----- mandatory
}
```

**Comment by lynshi** [comment]
You need to add the `--sdk-auth` flag to the `create-for-rbac` command.

**Comment by jeepdude1980** [comment]
I'm gunna find you fools

**Comment by jeepdude1980** [comment]
I've been hacked remove thks

**Comment by eaarora-ms** [comment]
@lynshi  Thanks for pointing it out.

@bruno-brant  @ardacetinkaya  As per the document here: https://github.com/Azure/login#configure-deployment-credentials 
you have not added the  --sdk-auth flag to the create-for-rbac command. and hence the O/P is not in the correct format. Please add the flag.

Just tried it and it works fine.
