### ISSUE TITLE
Self-Hosted Github Runner in Azure VM using Managed Identity

### ISSUE THREAD

**Issue by jdelforno** [Azure/login#56]
Thanks for your efforts on writing this!

Is it possible to add support for Managed Identities using a self-hosted github runner in an Azure VM / Container?

As the Action already uses Az Module, I'd hope it'd be a simple switch to use MSI ala: https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-4.7.0#sign-in-using-a-managed-identity

Doing so would remove any potential for secret leakage anywhere along the line.

Cheers,
JD

**Comment by aksm-ms** [comment]
@jdelforno Thanks for the suggestion. I will mark it as enhancement and we will work on it.

**Comment by mudunuax** [comment]
Hi. Can you please share any timeline, if there is, on when this enhancement will be merged to the master?

**Comment by jdelforno** [comment]
> 
> 
> I am also curious about the timeline.
> 
> Workaround, for now, would be something like this:
> 
> ```
>     - name: Azure CLI script
>       uses: azure/CLI@v1
>       with:
>         azcliversion: 2.0.72
>         inlineScript: |
>            az login --identity
> ```
> 
> However, it would look cleaner if there was an option to do:
> 
> ```
>     - name: Login via Az module
>       uses: azure/login@v1
>       with:
>         identity: true
> ```
> 
> where another parameter like `username` is an optional value of <client_id|object_id|resource_id>

That's a great step forward though. Especially with the Github Branch / Environment with secret protection in place.

**Comment by cmatskas** [comment]
Hi all, can someone let me know if this was ever implemented? We have a working solution [here](https://github.com/Azure/login/pull/68) that JP recommended earlier and I would love to freshen up and send a PR if you're open to it?? @aksm-ms @BALAGA-GAYATRI

**Comment by mikeviviani** [comment]
Hi
adding here the interest of this feature. Any plan to release it?

**Comment by dstratman-fi** [comment]
Team, this is sorely needed.  This feature for the azure cli has been available for some time, and this looks like an easy win / implementation, can we get an estimate or timeline?

**Comment by YanaXu** [comment]
This feature is supported by `v1` and `v1.5.1` now.
