### ISSUE TITLE
actionnis unreluable once azure is busy (endpoints busy euth requests?)

### ISSUE THREAD

**Issue by antst** [Azure/login#59]
Last night azure was busy somehow (for example, creation of service principals from az cli  would take few attempts, before succeed). And azure/login was completely unreliable. At least 9 out of 10 attempts would result in authorization not working for the same CI setup which was smooth few hours before. And if workflow has another authorization (k8s for example, which had last night the same problems), then chance of success is 0.1*0.1=0.01 :)

I presume, azure/login has to do more attempts before it fails. Otherwise it is difficult to rely on CI.

**Comment by arjgupta** [comment]
@antst az cli also performs retries of the request on its own. This seems like an extreme case where the login endpoint was facing some issue. And so it is possible adding retries from the action might not help too much. I am closing this issue. If you face this issue frequently, please feel free to reopen and we can further investigate it.
