### ISSUE TITLE
set-env is deprecated

### ISSUE THREAD

**Issue by jakebailey** [Azure/login#62]
I see this in my actions log when running this action:

> Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands

It appears this action uses an outdated version of `@actions/core` (older than v1.2.6, at least). Can the dependency be updated and a new version published so that this action doesn't stop working when `set-env` is no longer supported?

**Comment by mgrabarz** [comment]
I think there is already PR to fix that: https://github.com/Azure/login/pull/60

Likely we need to Release v1.2 so everyone can use it in their workflows.

**Comment by apclouds** [comment]
Hi @mgrabarz will this change the name of command "set-env"? We are working on a learn module using this in one of our example and would like to know before we publish.

**Comment by jakebailey** [comment]
`set-env` is a detail of GitHub Actions; they have a new method to set environment variables that doesn't involve printing to stdout. See: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

This doesn't affect actions that use the `@actions/code` library; the library itself now uses the new method and an upgrade to this action's dependency is all that's needed. Changes to other actions or workflows wouldn't be in scope of fixing a single action.

**Comment by mgrabarz** [comment]
@apclouds as Jake mentioned, `@azure/login` action is simply using the old version of core.exportVariable function from `@actions/core`. 
Bumping library will stop producing this warning in logs.

See e.g.: https://github.com/Azure/login/blob/master/src/main.ts#L21

**Comment by AmrutaKawade** [comment]
This is fixed #60 use tag v1

**Comment by apclouds** [comment]
Thanks for the detail!
