### ISSUE TITLE
Developer guide?

### ISSUE THREAD

**Issue by pearcec** [Azure/login#65]
Would it be possible for someone to write up a quick developer guide?

**Comment by aksm-ms** [comment]
@pearcec Can you please explain what is the developer guide you are looking for?

**Comment by pearcec** [comment]
I wanted to fix bugs and build.  I was looking for a document that explains the process a developer would follow to build and run.

**Comment by aksm-ms** [comment]
@N-Usha Can you please take a look at this? Should we add a developer guide in this repo itself?

**Comment by aksm-ms** [comment]
@pearcec Thanks for suggesting this. We are looking into this internally and we will work on it.
In general, following are the steps to be followed:

1. Fork the repo
2. Pull the repo to your local on master branch
3. run "npm install"
4. add your changes to .ts files
5. add unit tests and build 
6. To check if unit tests pass, run "npm run test"
7. To build files, run "npm run build"
8. Checkin .ts files, unit tests, .js files and node_modules to your fork.
9. Currently actions cannot be tested end to end on your local, so please create a workflow and point it to your org/repo@branch and test if your changes are working end to end.
10. Once code is tested and unit tests are added, please raise a PR against azure/login master branch.
11. Include .ts files, .js files, unit tests and documentation change if any on README, action.yml. Do not add node_modules to PR.

After code review and approval, your code changes will be merged to master.

**Comment by 20shivangi** [comment]
@N-Usha Please take care of the documentation for the above.

**Comment by maisoenaingtun** [comment]
Support {{#each}}-{{else}}

**Comment by kaverma** [comment]
Fixed the issue with PR #99
