### ISSUE TITLE
Does the action support SPN inputs created at a management group scope?

### ISSUE THREAD

**Issue by Ganeshrockz** [Azure/login#70]
The action looks like accepting a required `subscriptionId` as an input whereas the same will not hold true in case of SPNs created at a management group scope. ADO based service connections accept a management group Id in such scenarios. Is this scenario supported by the action or is this something that needs to be considered as an enhancement to the current behavior?

**Comment by nadesu** [comment]
@aksm-ms - pls revert on this query

**Comment by aksm-ms** [comment]
@Ganeshrockz Currently action only supports "subscription" scope. Adding management scope can be taken as enhancement and we will work on it.
