### ISSUE TITLE
azure/login@v1.1 doesn't work with SPN created in Azure Gov Cloud

### ISSUE THREAD

**Issue by zainuvk** [Azure/login#71]
GitHub Actions with  Azure Gov Cloud doesn't seems to be working with SPN.The error it shows is while logging  with SPN details.
![image](https://user-images.githubusercontent.com/13005040/96419731-2ab2bc00-1212-11eb-86ed-b6edab433c5e.png)

This file would need a  change  to add support for az cloud set --name AzureUSGovernment
https://github.com/Azure/login/blob/master/src/main.ts

**Comment by aksm-ms** [comment]
Added support in azure/login@v1 for Sovereign clouds.
