### ISSUE TITLE
Content is not a valid JSON object

### ISSUE THREAD

**Issue by justinyoo** [Azure/login#8]
Similar to #5, I created a service principal and got the result of

```json
{
  "clientId": "<GUID>",
  "clientSecret": "<GUID>",
  "subscriptionId": "<GUID>",
  "tenantId": "<GUID>",
  "activeDirectoryEndpointUrl": "https://login.microsoftonline.com",
  "resourceManagerEndpointUrl": "https://management.azure.com/",
  "activeDirectoryGraphResourceId": "https://graph.windows.net/",
  "sqlManagementEndpointUrl": "https://management.core.windows.net:8443/",
  "galleryEndpointUrl": "https://gallery.azure.com/",
  "managementEndpointUrl": "https://management.core.windows.net/"
}
```

However, I got the following error when I login to Azure:

> Content is not a valid JSON object

![image](https://user-images.githubusercontent.com/1538528/70575365-79f38d80-1bfa-11ea-8cfb-115bb2a3c48e.png)

I omitted, just in case, unnecessary properties from the JSON object like:

```json
{
  "clientId": "<GUID>",
  "clientSecret": "<GUID>",
  "subscriptionId": "<GUID>",
  "tenantId": "<GUID>"
}
```

And the result is still the same. What am I missing?

**Comment by justinyoo** [comment]
I found why I got the error. Here's my action:

```yaml
- name: Login to Azure
  uses: Azure/login@v1
  env:
    CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  with:
    creds: $CREDENTIALS
```

I intentionally used the environment variable at the step level. However, it didn't pass to the parameter. Can we use the environment variable to capture secrets from the repo?

**Comment by N-Usha** [comment]
Thanks @justinyoo for using our action and providing feedback. Adding @SumiranAgg to respond your queries.

**Comment by aksm-ms** [comment]
@justinyoo Please update your workflow as follows:

- name: Login to Azure
  uses: Azure/login@v1
  env:
    CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  with:
    **creds: ${{ env.CREDENTIALS }}**

Reference - https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#env-context

**Comment by justinyoo** [comment]
@aksm-ms Thank you!

**Comment by justinyoo** [comment]
I confirm the parameter has been introduced.

https://github.com/Azure/login/blob/ed39f6a8e2e82929e9fb7203ba551f89379e2545/action.yml#L4-L5

**Comment by hydrocortisone** [comment]
But this mistake is in docs everywhere...

**Comment by SuperHarmony910** [comment]
Ohhh, so not just pasted in as XML from the publishProfile file

**Comment by mahomedalid** [comment]
I had the same issue, my issue was that the variable should not have end-of-line characters, it should be just one line. The output from my command was a beautified json, and I just needed to remove the new-line stuff.
