### ISSUE TITLE
set-env is deprecated

### ISSUE THREAD

**Issue by ricardojosegomezulmke** [Azure/login#82]
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by aksm-ms** [comment]
@ricardojosegomezulmke We have already addressed this issue. Are you facing this issue? If so, please send workflow and workflow log runs.

**Comment by aksm-ms** [comment]
Closing issue since it is already fixed in action. Please feel free to reopen if you are facing any issues.

**Comment by pjoe** [comment]
Seeing the same issue, using:

```
      - name: Azure login
        uses: azure/login@v1.1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
```

Gives following error ouput:

```
Run azure/login@v1.1
Error: The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by pjoe** [comment]
Ok, I solved it by changing to: `uses: azure/login@v1`
