### ISSUE TITLE
SAMPLE WORK

### ISSUE THREAD

**Issue by AGASTINRAJ** [Azure/login#86]
https://foeat-my.sharepoint.com/:x:/g/personal/1837010047_foeat_onmicrosoft_com/EbgthNXb2xxApVwVn_jXXaMBeGXmOcqDJBc4ia3KobMzbw?e=DzjreM

**Comment by AGASTINRAJ** [comment]
..

**Comment by aksm-ms** [comment]
@AGASTINRAJ Please do not create issues in this repo which are not related to [Azure Login action](https://github.com/Azure/login/issues/86).
