### ISSUE TITLE
How to do `az login --identity` ?

### ISSUE THREAD

**Issue by AllanXu49** [Azure/login#87]
Hello,

My self-hosted runner has Managed Service Identity (MSI) enabled. 
According to this doc:
https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli#sign-in-with-a-managed-identity

In a command prompt, I need to run `az login --identity`

How do I do the same with "GitHub Action for Azure Login"?

Thank you,

**Comment by aksm-ms** [comment]
@AllanXu49 Currently azure login action does not support MSI. It is in our backlog and we will add support.

**Comment by rafi-fisker** [comment]
When will this be added?

**Comment by AzySir** [comment]
This really needs to be added - now I just have to run a script for this so I don't use your provider anymore...
