### ISSUE TITLE
Confusing credentials docs

### ISSUE THREAD

**Issue by reilem** [Azure/login#95]
The credentials docs gives the first impressions that this action only works with web apps, by making it seem that `{app-name}` is a mandatory field. However it is only much further down that you specify that you can omit everything in the scope after `providers`. Not everyone uses az-cli for web apps, some use it for settings specific metadata or uploading things to storage accounts. Please leave docs open for those possibilities.

I would suggest small small changes that:
1. Gets to the point
2. Also includes a link to the formal docs of this command for those who want more info

For example:

>2.  Use the az ad sp create-for-rbac command to create a service principal and assign a Contributor role:
> 
> For web apps (also more secure)
> ```
> az ad sp create-for-rbac --name "{sp-name}" --sdk-auth --role contributor \
>     --scopes /subscriptions/{subscription-id}/resourceGroups/{resource-group}/providers/Microsoft.Web/sites/{app-name}
> ```
> For other usage
> ```
> az ad sp create-for-rbac --name "{sp-name}" --sdk-auth --role contributor \
>     --scopes /subscriptions/{subscription-id}/resourceGroups/{resource-group}
> ```
> Replace the following:
> 
> - {sp-name} with a suitable name for your service principal, such as the name of the app itself. The name must be unique within your organization.
> - {subscription-id} with the subscription ID you want to use (found in Subscriptions in portal)
> - {resource-group} the resource group containing the web app.
> - [optional] {app-name} if you wish to have a tighter & more secure scope, use the first option and replace this with the name of the web app.
> 
> This command invokes Azure Active Directory (via the ad part of the command) to create a service principal (via sp) specifically for Role-Based Access Control (RBAC) (via create-for-rbac).
> 
> The --role argument specifies the permissions to grant to the service principal at the specified --scope. In this case, you grant the built-in Contributor role at the scope of the web app in the specified resource group in the specified subscription.
> 
> If desired, you can omit the part of the scope starting with /providers/... to grant the service principal the Contributor role for the entire resource group:
> 
> For security purposes, however, it's always preferable to grant permissions at the most restrictive scope possible.
> More info can be found [here](https://docs.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#az_ad_sp_create_for_rbac)

Let me know if you are open to a PR for this, or would like to do it yourselves 😄

**Comment by aksm-ms** [comment]
@N-usha Can you please take a look at this?

**Comment by aksm-ms** [comment]
@reilem Please raise a PR.
