### ISSUE TITLE
There was an error fetching tenants

### ISSUE THREAD

**Issue by MinhTraHong** [Azure/login#98]
I have nightmare with Azure portal login. I reveiced that message and there is nothing in my Azure portal blade, my resource group, MySql DB, function app, Ad, ...

The error happen on my own account and company account. I always separate these accounts with 2 browsers.

Detail:
There was an error fetching tenants. Please reload the portal to try again. If you wish to switch tenants, you can sign in directly into a tenant by specifying the tenant domain or tenant id as part of the portal URL. For example, https://portal.azure.com/tenantdomain.com

**Comment by ds-ms** [comment]
It could be due to Azure Active Directory outage declared about 10 hours ago. 
Check out this tweet by Azure Support: https://twitter.com/AzureSupport/status/1371544292502564866?s=20

**Comment by maisoenaingtun** [comment]
{{/ https://twitter.com/AzureSupport/status/1371544292502564866?s=20}} 
{{/ https://portal.azure.com/tenantdomain.com}}

**Comment by maisoenaingtun** [comment]
{{There was an error fetching tenants #98}}

**Comment by kaverma** [comment]
> It could be due to Azure Active Directory outage declared about 10 hours ago.
> Check out this tweet by Azure Support: https://twitter.com/AzureSupport/status/1371544292502564866?s=20

Closing this as there was an AAD outage at that time. Please reply or comment if you still see issues. Thanks
